### ISSUE TITLE
Use CFBundleShortVersionString instead of CFBundleVersion

### ISSUE THREAD

**Issue by yocory** [adjust/ios_sdk#119]
Currently Adjust is using CFBundleVersion when it sends info to the server. This is the build number and not the applications version number (CFBundleShortVersionString). A single version might have the build number incremented many times while the version number stays the same while it is being tested on Test Flight. Currently this field when looking at adjust (in our case using the web hooks) is very confusing as it is possible to have many builds with the same number, but once the app is released it can never have the same version number.

**Comment by nonelse** [comment]
We use `CFBundleVersion` because it provides the most information of the version of the app that was used to upload to the store. Although it is usually the same as the public app version, it can also be different. We will add a `app_version_short` in the next version that can be used as a placeholder.

**Comment by yocory** [comment]
Thanks, having that change makes our usage of the web hooks a much better.

**Comment by uerceg** [comment]
Done in https://github.com/adjust/ios_sdk/pull/120.
