### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by ChitChips** [adjust/ios_sdk#144]
Any plan to support Carthage?

Currently we have this error, if we try to build your projet with Carthage :

 "Failed to discover shared schemes in project Adjust.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned"

**Comment by uerceg** [comment]
Hi @ChitChips 

We didn't have any request regarding Carthage and that is not something that is on our current roadmap. 

As far as I saw on Carthage GitHub page, they are claiming following:

```
Carthage only officially supports dynamic frameworks. 
Dynamic frameworks can be used on any version of OS X, but only on iOS 8 or later.
```

`Adjust.framework` you are finding on our `Releases` page is static framework. Maybe that's the reason why are you facing this error (just a guess). Anyway, soon we are going add Adjust dynamic framework as well to our GitHub repository and maybe then it will be possible to build it with Cartage. If we need to make extra effort in order to make it work with Cartage, we will take this in consideration and depending on priority, put it to our roadmap.

Cheers

**Comment by alvivi** [comment]
@ChitChips adjust framework has nothing complex preventing the build as dynamic framework. Just fork the project and follow the instructions on Carthage page to fix their old days `.xcodeproj`. Alexander Kolov did that and published his work, so you can add `github "akolov/adjust" "dynamic-framework"` into your `Cartfile`.

**Comment by ChristianKienle** [comment]
++

**Comment by timonus** [comment]
+!

**Comment by uerceg** [comment]
@ChitChips @ChristianKienle @timonus We have made `carthage` branch to test our SDK with Carthage. It would be great if you can share some feedback with us once you try it. Try adding following to your `Cartfile`:

```
github "adjust/ios_sdk" "carthage"
```

Please have in mind that we'll eventually merge this branch, so from that point of time you won't need `"carthage"` anymore, but I'll keep you up to date.

Cheers

**Comment by ChitChips** [comment]
It works great with a full swift project using : `import AdjustSdk`

Thanks @uerceg for your time. I hope you will merge this branch ;)

Cheers

**Comment by timonus** [comment]
Awesome, excited to see that merged!

**Comment by uerceg** [comment]
For update's sake, we made PR for this issue, once reviewed, it will be merged: https://github.com/adjust/ios_sdk/pull/147

**Comment by timonus** [comment]
Terrific!

**Comment by uerceg** [comment]
It's merged: https://github.com/adjust/ios_sdk/releases/tag/v4.5.0

We left `carthage` branch still, until everyone makes transition from that branch in `Cartfile`. If you could just confirm that everything now works w/o `"carthage"` parameter in `Cartfile`, I think we can close this issue then.

Thanks in advance!

**Comment by ChitChips** [comment]
Works great! No issues!

**Comment by uerceg** [comment]
Awesome. If any problem regarding this issue shows up, feel free to reopen this issue.
