### ISSUE TITLE
Deferred deeplinking

### ISSUE THREAD

**Issue by tsaizhenling** [adjust/ios_sdk#148]
hi, we are getting reports that some times, the deferred deeplinking after an install does not work. but sometimes it does.
from our logs, when it does not work, looks like the app did not recieve the deeplink
we are currently on 4.2.7, which is compiled against iOS9

can you explain what exactly happens during a deferred deeplink so that we can debug this further?

**Comment by LeJohnDuff** [comment]
Hey,

Thanks for reaching out! Can you contact support@adjust.com so that we can have a look?

Thanks!

**Comment by uerceg** [comment]
@tsaizhenling Did you manage to solve your issue?

**Comment by uerceg** [comment]
@tsaizhenling Our deferred deep linking is functional with all iOS versions. In terms of how to implement deep linking in you app, you can check the updated docs in here: https://docs.adjust.com/en/universal-links/

If you encounter any issues with this, feel free to reach us in here or by sending us an email on support@adjust.com.

Cheers

**Comment by Kwon11** [comment]
Hi @uerceg, I am looking for help / information on how to test deferred deep linking.

I can't go through the normal app store flow, and i have been unable to find a workflow for testing deferred deep linking. I have tried clicking a deep link, then building and running the application from xCode to simulate an install. 

The callback to adjustConfig.setDeferredDeeplinkCallbackListener does not get called. I figure it is related to my workflow and not a problem with adjust.

https://github.com/adjust/react_native_sdk#deeplinking-deferred     does not go into detail on how to test, and I cannot find any more information in the docs regarding deferred deep linking.

Can you give any suggestions on how to test deferred deep links?

**Comment by uerceg** [comment]
Hi @Kwon11 

Test should look something like this:

1. W/o having your app installed on the device, click Adjust tracker URL which contains `deeplink` parameter (so, not scheme based URL like maybe yourapp://something, but rather link which looks like https://app.adjust.com/abc123?deep_link=yourapp%3A%2F%2Fsomething where `abc123` is your test tracker token and `yourapp` is scheme your app handles and which you have added to Adjust dashboard).
2. After clicking the link, you'll get redirected to the App Store to your app page if it's published in there.
3. Close the store and simply install your app to your test device from Xcode.
4. After SDK has been initialised and install tracked, you're gonna get deferred deep link content.

Thing you are maybe not doing is properly forgetting your test device from our backend. Just uninstalling app from your device and doing the steps described above is not enough, since once you have made install of your app on test device, our backend remembers that it happened and won't repeat install scenario on that device (even though you have uninstalled it on your test device and reinstalled). In order to recreate first install ever scenario, after uninstalling your app from test device, you should go to test console in Adjust dashboard and forget your test device. After successfully uninstalling your app and forgetting the test device in our dashboard, doing the flow from above should deliver deferred deep link information to you.

Let us know if you managed to test it or if you have any other questions.

Cheers

**Comment by Kwon11** [comment]
thank you! I was not deleting the device from adjust dashboard.

**Comment by surajthomask** [comment]
@uerceg  I followed the exact steps mentioned by you, still no luck, deferred deeplinking is not working for me. Testing in iOS 10.3.3, and is using Paypal, FBSDK and Firebase deeplinks in the same app. All other scenarios are working for me except deferred deeplinking from adjust.

**Comment by uerceg** [comment]
@surajthomask 

Hm, that's odd. Do you maybe have dedicated AM that can help you with setting up testing environment for this? If not, feel free to write to support@adjust.com, reference your comment in there and we can continue from there, since in order to debug that, I would need you to tell me stuff that are not to be shared in public.

Cheers

**Comment by surajthomask** [comment]
@uerceg Thanks for the quick reply man. The SDK in our repo was kind of old, looks like really really old.:-( Updated the sdk and everything is working fine. I was about to arrange a call with the support, which is not needed anymore I guess. Once again thanks for the quick reply :+1:

**Comment by uerceg** [comment]
Awesome, glad that it worked for you and thanks for letting us know. :+1:

**Comment by marioradonic** [comment]
> Hi @Kwon11
> 
> Test should look something like this:
> 
> ....

Hey @uerceg, should this deferred deeplinking scenario work when we have setup custom store urls?
We are using hockeyapp for distribution of staging builds, and I cannot get `adjustDeeplinkResponse` delegate callback to fire, even after following your instructions.

btw. maybe this short instructions on how to test deferred deeplinking, especially forgeting the device from adjust, should be in the documentation :)

**Comment by uerceg** [comment]
Hi @marioradonic 

Deferred deep linking mechanism itself is agnostic towards pretty much everything except the fact that one should make a click on Adjust tracker URL and make an install of an app on the device afterwards.

Lemme try to write down step by step instructions which should be followed to see that deferred deep link is reaching the SDK (and your app) after an install:

```
1. Uninstall your app from test device.
2. Forget your test device in the testing console.
3. Click on the Adjust tracker URL which has deep link parameter properly added to it (correctness of tracker URL is implied in here). This click will redirect you to App Store where your current app version is or it won't in case you didn't publish it yet. What ever happens, feel free to ignore it.
4. Install your app to your test device. Again, how ever you want - debug build from Xcode, from Test Flight, from Hockey app, from App Store, by loading custom IPA file, doesn't matter.
5. After app is installed and SDK started, backend should recognise that click on above mentioned tracker URL happened from this device and give us back the content of your deep link parameter which will be forwarded to deep link callback which you have implemented in your app.
```

That should be it. One thing exist in here which should maybe be checked in case you never see deferred deep link arriving to your app -> when creating new apps in Adjust dashboard, fingerprinting is switched **OFF** by default. Which means that if you make tracker URL w/o your test device ID which looks something like this https://app.adjust.com/abc123?deep_link=my-mighty-scheme://some-random-stuff (I didn't encode URL properly for clarity purposes), backend will not be able to match this click to incoming install from your test device, thus it won't give us deferred deep link either (you can double check this by checking attribution callback and whether install you make is getting attributed to organic tracker or, as it should in this case, `abc123`). If this is maybe the case, then you need to either turn fingerprinting **ON** (this is probably not something developer wants to turn ON by default just for testing stuff without consulting people from your company is this something you really want to do, because it affects production traffic immediately as well) or to build URL which will contain your test device ID in it, so our backend would be able to match click with an install (so that URL looks something like: https://app.adjust.com/abc123?idfa=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&deep_link=my-mighty-scheme://some-random-stuff).

With all these things in mind, things would simply need to work well.

And regarding instructions on how to test these things being part of README, yeah, it maybe makes sense, but our README is already super bloated and I think that official docs on Adjust website contain these things maybe somewhere, so we're in eternal struggle what to put in README and not to make it a novel which people will just chose not to read because of it's size and make some dummy integration mistakes. :) But thanks for the advice, we'll definitely see what can be done on that topic.

**Comment by marioradonic** [comment]
Thank you very, very much @uerceg. The fingerprinting was off by default, as soon as I turned it on I got it working :)

Regarding documentation, I haven't been able to find these "tips" anywhere. Especially forgetting the device and fingerprinting must be on. Those things make perfect sense now when I understand how deferred deeplinking works, but two days ago I had no clue why it doesn't work.

Anyways, thanks for your quick and thorough response, much appreciated 👍

**Comment by uerceg** [comment]
Glad it worked. 🎉 

Will forward your feedback to teams in our company which are in charge of the docs and hopefully we can make this a bit more clear in the future.

Cheers! 🍺

**Comment by SherifKamalSalem** [comment]
Hi @uerceg please give my steps How can I debug universal link by installing the app from xcode on my device, because when I tried to open the link it redirected to app store not the app even it's already installed?

**Comment by uerceg** [comment]
Hi @SherifKamalSalem,

Have you checked [this chapter](https://github.com/adjust/ios_sdk#deeplinking-setup-new)? Have enabled associated domains for your app in Apple developer portal for and also later in the Xcode project?

Pretty much as long as you're clicking on universal link which you associated with your app and app is not being opened even if installed, it's should be indicator that something is not done properly with universal linking setup.

**Comment by SherifKamalSalem** [comment]
Now it's open the app but only on home screen I tried to debug it by enabling "Wait for executable to be launched" but the method of continue userActivity is not triggered anymore so I can't test it
I already checked the adjust documentation and follow it carefully but universal deep linking still not working.

**Comment by uerceg** [comment]
Hi @SherifKamalSalem 

Sorry for a bit of delay in responding. Feel free to test without `Wait for executable to be launched`. How does the link you are testing with look like?
