### ISSUE TITLE
Unable to read iAd details

### ISSUE THREAD

**Issue by JDandini** [adjust/ios_sdk#152]
After installing adjust vía cocoapods and following the instructions [written here](https://github.com/adjust/ios_sdk) I'm getting this:

```
[Adjust]v: Attribution file not found
[Adjust]d: Read Activity state: ec:0 sc:1 ssc:10 ask:1 sl:2675.9 ts:1324.6 la:1451317334.4
[Adjust]d: Package handler read 0 packages
[Adjust]d: iAd with 2 tries to read v3
[Adjust]d: ADJUST_NO_IAD or TARGET_OS_TV not set
[Adjust]d: Wrote Activity state: ec:0 sc:1 ssc:11 ask:1 sl:2732.9 ts:1324.6 la:1451317391.4
[Adjust]i: Started subsession 11 of session 1
[Adjust]d: Session timer fired
```

The setting up is Ok I passed from installing the pod to step 4  and I have no idea what to do if you be so kind to help me with this I will be happy. Have a nice day.  Just for kicks I add the response of my terminal with the pod version.

Have a nice day
```
$pod --version
0.39.0
```

And my pod file looks like this:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
.
.
.
pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v4.5.0'
```

**Comment by uerceg** [comment]
Hi @JDandini 

Recently, Apple has changed the way how iAd clicks are processed and named it iAd v3. Our SDK is checking if session / install is maybe coming from an iAd click. Since we can not be sure which iAd version is app which is running with our SDK inside uses, first we try to parse the newest version of iAd response, if we fail, we still try the older version to see if user came to the app from the iAd click. And for debugging sake, we added these lines to log output so that we can follow the flow of these checks. If you are not dealing with iAd campaigns, feel free to ignore those messages, because they are "normal" thing you will see in log output.

If you have any further questions or concerns, feel free to ask.

Cheers

**Comment by JDandini** [comment]
Thanks a Lot i was worried because I'm not have access to the dashboard :P but thank you for the answer

**Comment by MrPleaze2015** [comment]
We are 1FOREVERFREEDOM.NET
I'm a D.O.N.T kind of person! Call me Mrpleaze01.htm WISDOM'PASSION'LEGACY 1rightchoiceorganizationsupport.zendesk.com
