### ISSUE TITLE
I Have crash -[UIDevice adjTrackingEnabled]:

### ISSUE THREAD

**Issue by AzotKZN** [adjust/ios_sdk#158]
I manual setup AdjustSDK, today.
When i build app, i have crash: 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIDevice adjTrackingEnabled]: unrecognized selector sent to instance 0x15da66b0'

Before the crash on the console is written:
[Adjust]a: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing

**Comment by uerceg** [comment]
Hi @AzotKZN

Add -ObjC to Other Linker Flags settings in your project and try again.

**Comment by uerceg** [comment]
Did -ObjC solve your issue?

**Comment by AzotKZN** [comment]
Yes, thank you!

**Comment by uerceg** [comment]
No problemo. :+1:

**Comment by kivannc** [comment]
Is there a way to use library without adding -Objc flag? Parse sdk doesnt work when -Objc flag is set.

**Comment by uerceg** [comment]
@kivannc Well, you can maybe try following instead of adding `-ObjC` flag:

If we assume that app structure looks like that (I have placed our `AdjustSdk.framework` in `Adjust` folder), just as an example:

![screen shot 2016-03-21 at 13 05 40](https://cloud.githubusercontent.com/assets/1741635/13918180/da8e8bba-ef65-11e5-99ad-4fd641a73563.png)

Then, instead of adding `-ObjC`, you can try to force load our library only (not to force load them all if you don't want). You need to point to `.a` library file path after stating `-force_load` parameter in **Other Linker Flags**. In this example you should add following as parameter:

```
-force_load $(SRCROOT)/AdjustExample/Adjust/AdjustSdk.framework/Versions/A/AdjustSdk
```
Give it a try and let me know if it worked for you.

Cheers

**Comment by kivannc** [comment]
Thank you @uerceg.  I've added the library with different option. It is working with parse framework right now. I will try this solution when I encounter the same problem on a different project.

**Comment by uerceg** [comment]
:+1: Glad it worked.
