### ISSUE TITLE
Compile errors when adding the Dynamic - AdjustSdk.framework to Cordova iOS project

### ISSUE THREAD

**Issue by lumierephoto** [adjust/ios_sdk#180]
I'm having issues with this part of the integration instructions for the iOS SDK:

"You can also choose to integrate the adjust SDK by adding it to your project as a framework. On the releases page you can find two archives:

AdjustSdkStatic.framework.zip
AdjustSdkDynamic.framework.zip
Since the release of iOS 8, Apple has introduced dynamic frameworks (also known as embedded frameworks). If your app is targeting iOS 8 or higher, you can use the adjust SDK dynamic framework. Choose which framework you want to use – static or dynamic – and add it to your project before continuing with step 3."

I've added the dynamic framework and added it, but I get a compile error when I build the project.

       dyld: Library not loaded: @rpath/AdjustSdk.framework/AdjustSdk
       Referenced from: /Users/HAL9000/Library/Developer/CoreSimulator/Devices/F1CF27CD-327F- 499F-8B30-414E242CDFF3/data/Containers/Bundle/Application/89085F88-C368-46AF-AE7C- 1F343D9E61C4/Solitaire.app/Solitaire
        Reason: image not found

So I'm not sure that it is necessary for me to add this framework or can I just add the Adjust SDK from the Sources.zip?

If I remove the dynamic AdjustSdk.framework, then the app compiles and can be tracked in sandbox mode in the Adjust dashboard.

I'm building with Xcode 7.3 and iOS 9.3

**Comment by uerceg** [comment]
Hi @lumierephoto 

First to ask you - why are you using our native iOS SDK in your Cordova app? For that, we have the adjust Cordova SDK which can be found in here: https://github.com/adjust/cordova_sdk/

You can add our plugin to your Cordova app by running:

```
cordova plugin add com.adjust.sdk
```

**Comment by lumierephoto** [comment]
@uerceg Because the Cordova plugin didn't work. The native iOS SDK does work though. I believe my client only wants to track, so for now the iOS SDK will be fine. 

Could you answer my question about the integration with the dynamic SDK? Is it necessary? And if so, why am I getting errors in the console. 

By the way, I've tried the Static SDK and the non-Bitcode SDK and both gave similar errors in the console. Compiler errors.

**Comment by uerceg** [comment]
Well, first thing to check if you are adding dynamic framework to your app - did you add it to both, `Embedded Binaries` and `Linked Frameworks and Libraries` section of your target's settings?

<img width="797" alt="screen shot 2016-03-28 at 19 15 14" src="https://cloud.githubusercontent.com/assets/1741635/14084124/9b8caa64-f519-11e5-9c1a-75d20bfbc203.png">

**Comment by lumierephoto** [comment]
No, I didn't. Just the Linked frameworks and Libraries.

Let me ask you a question as it's not real clear in the instructions. 

Do I have to add this Dynamic framework (I'm targeting iOS 8 and above) AND the Adjust folder SDK in the SourceCode.zip? Or is it redundant to add this dynamic framework as well as the Adjust folder?

The reason why I am asking is because with just the Adjust folder in my project along with the few lines of code in the App Delegate the app install is being recorded in the Adjust dashboard. So is the Dynamic framework even necessary?

**Comment by uerceg** [comment]
Under the hood you basically have two choices how to add our framework:

- By adding complete source of our SDK directly to your app
- By using some of our frameworks (static or dynamic one)

In our README, we are assuming most people will use some of the frameworks and we're advising them how to add it via some 3rd party tools like `Carthage` or `CocoaPods` in this section: https://github.com/adjust/ios_sdk/#basic-integration
In this section, we are not explaining in detail how to integrate static or dynamic framework in the app because we kinda assume that is well known iOS development practice which every user should be familiar with.

If user is not using any of those methods to add our SDK to his/hers app, then we are explaining how to do it by adding source code of our SDK directly to user's app in this section: https://github.com/adjust/ios_sdk/#1-get-the-sdk

It is fully up to you to decide which path to follow.

BTW, did you manage to get rid of the previously reported error or are you still facing it?

**Comment by lumierephoto** [comment]
To be clear, I've already added the SDK that is "Step 2. Add it to your project"

So you are saying to adding the dynamic framework is an alternative to adding the source. OK, that is probably it. I misunderstood and thought I had to add this framework as well as the source. 

I don't have any errors with the source SDK and is logging correctly and showing up in the dashboard.

**Comment by uerceg** [comment]
Great. Glad to hear that. I must say again that although in theory everything can be done properly, we strongly advise that if you are making Cordova app, you add our Cordova plugin, because we kinda assume that if you are developing your Cordova app, you are doing most of your development from JavaScript and not from native generated projects.

I would still advise you to give Cordova SDK a try and if you are having some difficulties with integrating it, feel free to open an issue in here https://github.com/adjust/cordova_sdk/issues and we would be happy to help you solve it.

Anyway, I am glad that everything works for you now. :+1: 

Cheers

**Comment by lumierephoto** [comment]
Yes, I understand. 

As far as I know, the client only wants to track installs. Of course, if they want to use more features, then yes I would have to use the Cordova plugin. 

I did install it, but wasn't able to track anything and of course nothing in the console either so not sure if it was working or not.

**Comment by uerceg** [comment]
It should be fairly easy to do that with Cordova SDK (to track installs). This is a bit "hacky" way for Cordova apps, but if it works for you, great.

If you would still like to solve it with Cordova SDK, I encourage you to open the issue in Cordova SDK repository and I will guide you through and answer all your questions. On the other hand, if you don't want to do that, also fine, it's fully up to you.

Cheers

**Comment by uerceg** [comment]
Also, to mention that using not corresponding SDK in your app (native iOS SDK in Cordova app in your case) is something we consider as **bad practice** and are strongly **discouraging** you to do. Those scenarios are not something we have fully tested and our native iOS SDK is not intended to be used in that scenario, although you might find a flawless way to make it work. These scenarios quite often can cause lots of troubles to developers and some really funky error cases on which we can lose lots of time in trying to help someone fix them. In these cases, we are unable to provide you support for any issue which pops up in this situation. On the other hand, if our Cordova SDK causes some issues for you, since it's a proper way how to integrate our SDK in your app, we'll be more than happy to help you with any issue you encounter.

Cheers

**Comment by lumierephoto** [comment]
OK, well I'll open another ticket and maybe you can help me with integration into my Cordova project because I wasn't able to get it to work.

**Comment by uerceg** [comment]
Great. Looking forward to hear from you. :+1:

**Comment by SoftwareEngieer** [comment]
Hi @lumierephoto,

I have same problem and i fix it like below:

**Add "AdjustSDK.framework" to the "Embedded Binaries" section of the "General" tab of the Xcode project settings. Then deleting the derived data and rebuilding.**
