### ISSUE TITLE
Cannot submit builds with V4.10.0 dynamic framework included

### ISSUE THREAD

**Issue by rpatel-zynga** [adjust/ios_sdk#239]
Getting the following errors:

<img width="871" alt="screen shot 2016-09-08 at 6 17 27 pm" src="https://cloud.githubusercontent.com/assets/1044617/18368977/d38718de-75f0-11e6-8c72-72f4b08ba0cf.png">

Please note, we're building our app with Xcode 8 GM.  We included the V4.10.0 SDK dynamic framework that was downloaded directly from the releases tab.

**Comment by uerceg** [comment]
Hi @rpatel-zynga

Sounds like the issue which was already opened: https://github.com/adjust/ios_sdk/issues/175

For the reference maybe this as well: http://leancodingnow.com/app-submission-issues/

Also check Bart van Kuik's answer in here http://stackoverflow.com/questions/30547283/submit-to-app-store-issues first and then pAKy88's and let me know if something helped you solve the issue.

**Comment by rpatel-zynga** [comment]
Uglješa:

Thanks for the response.  We are not using Carthage.  We simply download the pre-compiled dynamic framework from the Github releases page and add it as an embedded binary to our project.  Are you saying we need to add the script outlined in http://stackoverflow.com/questions/30547283/submit-to-app-store-issues to our build phase (after the phase that embeds the Adjust dynamic framework) and it should work?

Thanks,
Raj

**Comment by uerceg** [comment]
Hi @rpatel-zynga 

Thing is that our dynamic framework supports architectures for simulators as well (i386 and x86_64) because we wanted to enable users to try our SDK on simulators as well. This seems like to pop up as an issue on submission, and reason is that Apple doesn't allow apps to be submitted with simulator architectures being part of some framework which is added to the app.

`lipo` is the tool which can easily be used to strip unwanted architectures from framework. You can do that on your own or (to answer to your question above) you can add this script which is gonna strip unwanted architectures automatically.

I did this thing now on my own and here's the updated version of the framework w/o those architectures. Please, test it before submitting the app to the app store and let me know if everything went well.

If yes, we'll consider maybe updating the docs to explain to people how this can be done or maybe even add new framework version to our releases page where we'll be stripping these architectures.

Looking forward to hear from you soon.

Cheers

[AdjustSdkDynamic.framework.zip](https://github.com/adjust/ios_sdk/files/464082/AdjustSdkDynamic.framework.zip)

**Comment by rpatel-zynga** [comment]
Uglješa:

I appreciate the quick response.  I managed to test out that build phase script you pointed me to and am happy to say that all is well now.  We were able to submit the generated binary to iTunesConnect.

I’m going to suggest that you add some documentation to the main integration README file that outlines what one needs to do in order to generate submittable binaries if they choose to integrate the dynamic framework.  One thing I should add is that I needed to enable the Run script only when installing option because it was failing on another dynamic framework that we generate ourselves (when generating debug builds for the simulator or device we have it configured to only build for active architectures which means the internally generated framework is not considered ‘fat’ i.e. containing all valid architectures.  Screenshot below).

[cid:image001.png@01D20A8F.39B28E90]

Cheers,
Raj

**Comment by uerceg** [comment]
We started to attach two versions of our dynamic framework in releases page (https://github.com/adjust/ios_sdk/releases):

- AdjustSdkDynamic.framework.zip
- AdjustSdkDynamicWithoutSimulator.framework.zip

Hopefully this will be more useful to overcome these issues.

Cheers
