### ISSUE TITLE
Swift example - wrong Bridging header

### ISSUE THREAD

**Issue by philippb** [adjust/ios_sdk#252]
The bridging header file in the swift example needs to include
`#import <AdjustSdk/AdjustSdk.h>` instead of `#import <AdjustSdk/Adjust.h>` for the latest SDK version `v4.10.2`, Dynamic Framework.

**Comment by uerceg** [comment]
Hi @philippb

Indeed, it should, but our example apps in the repository are built in the way that they use static framework and that's why we are having that import in the bridging header file.

Changing it to `#import<AdjustSdk/AdjustSdk.h>` will pretty much solve issues for people who are using dynamic framework with our example app and cause issues for people who are using static one (which we kinda added to the repository as the default way) so there's no really silver bullet solution for this because way of how import statements are written is tied to the way how our SDK is being added to the app (from source / as static framework / as dynamic framework / CocoaPods / Carthage).

I hope it's fine with you if we just leave it as it is, but definitely true statement in this issue -> people who are using our Swift example app with dynamic framework should modify bridging header file and add import statement like you have suggested.

Cheers

**Comment by uerceg** [comment]
@philippb

Do you have any other questions regarding this issue or it can be closed?

Cheers

**Comment by uerceg** [comment]
Closing the issue, feel free to reopen it if you still think there's a reason for it.

Cheers
