### ISSUE TITLE
Deeplink dont open installed application

### ISSUE THREAD

**Issue by chematiks** [adjust/ios_sdk#268]
I try open link:
https://app.adjust.com/xxxxxx?deep_link=myapp://...
If i dont have app, opened appstore and after install app, application open my deeplink in app. 
But if i have app, always open only appstore, without redirect in app. 

I install adjust: 
      let environment = ADJEnvironmentSandbox //i try and production environment
      let adjustConfig = ADJConfig(appToken: appToken, environment: environment)
      adjustConfig?.delegate = self      
      Adjust.appDidLaunch(adjustConfig)

I implement method 
  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {

    if userActivity.activityType == NSUserActivityTypeBrowsingWeb {
      let url = userActivity.webpageURL
      Adjust.appWillOpen(url)
    }
    return true
  }
And of course i add URL scheme. 
If i try open only myapp://..., application work is fine. 
Please help me :)

**Comment by uerceg** [comment]
Hi @chematiks 

1. What is the iOS version of the device which you are using to test this flow?
2. Do you have universal links enabled in the adjust dashboard?
3. Do you have universal links enabled in your app?

Cheers

**Comment by chematiks** [comment]
Hi @uerceg! 
1. I use iphone6 with ios 10.2(14C92) 
2. Yes, i enable universal links in adjust dashboard. 
<img width="501" alt="2017-01-06 18 32 16" src="https://cloud.githubusercontent.com/assets/5111248/21716684/8786fede-d43e-11e6-88ba-b578c93e080f.png">
3. I add URL scheme and I implement in my application methods:
  func adjustDeeplinkResponse(_ deeplink: URL!) -> Bool  and another AdjustDelegate methods. 
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool 
  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool
If user not have app, then deeplink work is fine.

**Comment by uerceg** [comment]
Okay, for point 3, did you enabled support for `Associated Domains` in your Xcode app's project and added your short universal link to domains which your app handles like described in here? https://github.com/adjust/ios_sdk#deeplinking-setup-new

**Comment by chematiks** [comment]
yes, I add domains from adjust in format 
applinks:xxxx.adj.st 
<img width="474" alt="2017-01-06 18 40 57" src="https://cloud.githubusercontent.com/assets/5111248/21716842/c4983fb2-d43f-11e6-9d3c-34e63f81a9f9.png">

**Comment by uerceg** [comment]
Can you please check if your app gets opened by making a click to short universal link? So, put https://xxxx.adj.st/ on some webpage, open that page with browser and make a click on that link once app is already installed on your test device. I would like to check if universal link setup has been done properly.

**Comment by chematiks** [comment]
![img_9070](https://cloud.githubusercontent.com/assets/5111248/21720204/76b09622-d454-11e6-9011-f136013adf0e.PNG)

**Comment by chematiks** [comment]
ОТКРЫТЬ it is transalet is "Open"

**Comment by chematiks** [comment]
Hi @uerceg! 
Do you can help me? If i rigth understand, trouble connected with safari webkit... In Chrome link is worked, but dont work in Safari.

**Comment by uerceg** [comment]
Hi @chematiks 

Did you type in the short universal link into the Safari URL bar and loaded it? Or did you maybe copied the link, pasted it into Safari URL bar and loaded it?

**Comment by jdmoody** [comment]
@uerceg, I'm having the exact same problem as @chematiks.

I set up the proper iOS Bundle ID, App Prefix, and App Scheme in the Adjust Dashboard. I also set the Associated Domain provided by the Dashboard (xxxx.adj.st).

I created a test web page with the https://xxxx.adj.st link on the page. After I tap the link, I still get the "Url not found" page as shown above in the screenshot. **The problem only happens in Safari iOS, not Chrome iOS.** Chrome deeplinks link into the app properly. I also tried adding the tracker token to the test link (https://xxxx.adj.st/?adjust_t=abc123), but this doesn't work for Safari either. 

Universal links also work properly when not handled through Adjust. I'm testing on iOS 10.

**Comment by uerceg** [comment]
@jdmoody 

Which iOS version does your test device have?

**Comment by jdmoody** [comment]
@uerceg iOS 10.2 beta (14C5077b)

**Comment by RMPtc** [comment]
Hi, I'm having the same issue. Adjust links on Chrome and Opera Mini, opens the app as expected, but the Safari always sends me to the Appstore.
I'm currently on iOS 10.2.1 (14D27).

Any idea on how to fix the issue or a workaround?

Thanks

**Comment by NeoHuang** [comment]
@chematiks if you can see the `Open` banner at the top, it means the universal link is setup correctly.

but for some reason. Apple remembers user's last choice of opening the link with browser or app. and decided to open it with safari. it's described [here](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html) (search for `recent choices`). once you click the `Open` and next time you click the https://xxxx.adj.st . it will work.

the reason why it works when you click on https://app.adjust.com/xxxxxx?deep_link=myapp:// is: we still using javascript to make scheme based deeplink (non universal link) in Chrome. and it works perfectly in Chrome, but unfortunately the javascript way of opening your app and fallbacks to store breaks since apple introduced universal link. 

universal link is only used for safari and it has it's own restriction by Apple which we cannot do much

hope this helps

**Comment by lozhuf** [comment]
I have also seen this issue. It seems to me that the black-box nature of Adjust (and universal links in general) is deeply confusing, and as evidenced by the number of people struggling with this, it seems that Adjust's documentation is somewhat lacking.

One question regarding universal links that is not discussed in your documentation: what is the reason for enabling them in the Adjust settings? We still need to support the custom url scheme, and use the `app.adjust.com/...` link format, in order to be backwards compatible. Does it simply remove the "Open in <AppName>" alert, or are there other advantages? Are there any disadvantages to using the universal links (apart from always opening in the appstore if the user presses the wrong button)?

For the record, to reset your universal link `recent choice`, which makes universal links do as expected, long-press on the xxxx.adj.st url and choose `open in <appname>`... this will update your choice (see: http://stackoverflow.com/a/32745272/318834).

**Comment by NeoHuang** [comment]
@lozhuf thanks for your feedback. 

deeplink behaviour is not black-box nature of adjust. Universal link  is a feature of iOS. we are simply helping your setup easier and we are pretty open about how we implements it. you can read the details in our [tech blog](http://big-elephants.com/2016-02/dive-into-deep-linking/). 

the reason why universal link is needed is because since 9.2, the js way of using single URL be able to redirect to both App Store and open app stop working (because the "Open in" message box is no longer modal).  The disadvantage of Universal link is that it has some limit as described [here](https://www.adjust.com/overview/2017/03/02/universal-links-vs-deep-links/). But unfortunately, that's the limit of iOS which we don't have any control

**Comment by lozhuf** [comment]
@NeoHuang Thanks for your quick reply. 

Apologies if I sounded short - I understand that Adjust is working to improve apple's universal links. By black-box, I simply meant that from the SDK-user's POV, I call a url, Adjust does some useragent-based`forwarding magic`, asks Apple to open a link, and apple does some `recent-choice magic`. And then maybe it opens in the app or appstore, but it feels all rather opaque. That is obviously just a frustrating side-effect of hacking around apple's system... the main problem is that your documentation is rather unclear (I was not able to find a link to that tech blog article anywhere in the docs, for example).

Furthermore, though the engineers I have dealt with here on GH seem very helpful and well informed, your support channel seems to be giving me contradicting or nonsensical advice. So I would really like to double-check that the advice given for this issue by your support channel is something that might actually solve this problem - it seems like it is probably advice that has been given to others too.

Do I need to implement the `attribution callback`? I was asked to verify that I was implementing it (with no description of what to do in the callback). Based on standard delegate conventions, and the code's comments, an optional non-returning delegate method is simply for informational purposes. 
However, the supporter was adamant that I implement it in order for my deeplinks to arrive and be opened: `The deferred deep link is not arriving as part of the answer to the first session but as an attribution answer instead. In order to get that attribution answer along with the deferred deep link info, you need to implement the attribution callback in the SDK. I understand our documentation is not entirely clear and it may seem that attribution callback is optional.`

So, is this something I need to implement? Is there anything I need to do in this callback? If, as I suspect, this is not required, please let your supporters know they need to update their handbook.

Thanks for the help :)

**Comment by nonelse** [comment]
Hi @lozhuf, thanks for clarifying.
The attribution callback and the deferred deep link functionalities are indeed separated capabilities.
That question might come from an issue the sdk had until [v4.10.3](https://github.com/adjust/ios_sdk/blob/master/CHANGELOG.md#version-4103-18th-november-2016) where the deferred deep link feature was wrongly dependent on the attribution callback.
If you are using a more recent version, and we recommend to use the latest, you won't need to implement the attribution callback feature to have deferred deep link working.

**Comment by lozhuf** [comment]
@nonelse Great, thanks! :)

**Comment by avinz** [comment]
Hey, any news about this issue? Or it will not work anyway with safari?

**Comment by uerceg** [comment]
@avinz

This should work with Safari. Or at least mostly, having in mind last iOS versions. Seems that Apple actually managed to break universal linking with the relase of iOS 11.2 and as of that version (in conclusion with latest official one), having an app that handles certain universal link installed on your device and clicking on that link in Safari actually causes App Store to be opened, because upon app download and install as of iOS 11.2, iOS isn’t making a call to obtain associated domain JSON file to be aware of app’s association with certain domain. 

Good news from what we saw today with iOS 11.2.5 beta 3 is that they seem to have fixed the issue. Can you retry this flow with device that has iOS 11.2.5 beta 3 and see if it works for you?

**Comment by uerceg** [comment]
Please, feel free to reopen it if you still face the issue, but bare in mind that with iOS 11.2.5 beta 6 (current one), universal linking seems still to be broken.

**Comment by GabrielTargon** [comment]
This issue is still happening on iOS 11.4.1 and 12 with Adjust version 4.12.3.
When I open the link on Safari it send to the AppStore but when I open on Chrome it send to the app as it should.

The problem is when a user click on a banner on Facebook, Instagram or other social media or website it will send to Safari and the app will not be opened. This problem was solved? There is a workaround?

**Comment by NeoHuang** [comment]
Hi, @GabrielTargon thank you for your message. which link are you trying to use for safari? there is a limitation of deeplink in iOS Safari as mentioned above. You have to use universal solution to make it work. You can also contact our support to get more detailed clarification.

**Comment by GabrielTargon** [comment]
I'm using https://app.adjust.com/xxxxxx that redirect to https://xxxx.adj.st/xxxxx and them open the pop up to go to the App Store. But now I tested when open the link in Chrome, Instagram and Facebook and they redirect to the app, but it redirect to openURL method and not to continueUserActivity method, and I don't know why this is happening. And don't know why safari isn't working even when everything was setup (associated domain, method, configuration on adjust website).

**Comment by NeoHuang** [comment]
@GabrielTargon right. that's the limit of safari. as already mentioned in our [tech blog](http://big-elephants.com/2016-02/dive-into-deep-linking/) if the click happens outside of safari, a redirected universal link won't open the app. so we suggest to use https://xxxx.adj.st/xxxxx in your campaign and it should work.
for chrome, FB and instagram we will still fallback to javascript solution which try to redirect to scheme:// and it still works well. (but this solution won't work in safari)

**Comment by NeoHuang** [comment]
@GabrielTargon I'd suggest to contact our support team support@adjust.com to get more help on that, thanks.

**Comment by altayaydemir** [comment]
Hey there! As a recent lurker of this thread, thanks to everyone being kind and informative. 🤗 
Unfortunately, we are also suffering from this issue as of iOS 13. 😢
Did anyone come up with a solution for this?
Does Adjust have any related (hopefully resolved 😁) case in the support archive can be shared?
Thanks!

**Comment by uerceg** [comment]
Hey @altayaydemir 

This topic is being covered and handled by our integration team members who are not really watching public SDK repositories. My advice would be to reach out either to your dedicated account manager if you have one or if not, fire an email with your question to support@adjust.com.

Cheers
