### ISSUE TITLE
Not sending events until the app is moved into the background first

### ISSUE THREAD

**Issue by ynmehel** [adjust/ios_sdk#308]
Hi,

I have recently updated the SDK from `4.6.0` to `4.11.4`, which caused a couple of automated tests failing. When I investigated, I have realized that we are not receiving `AdjustDelegate` callbacks, namely the following methods are not called: 

```
- (void)adjustEventTrackingSucceeded:(ADJEventSuccess *)eventSuccessResponseData;
- (void)adjustEventTrackingFailed:(ADJEventFailure *)eventFailureResponseData;
- (void)adjustSessionTrackingSucceeded:(ADJSessionSuccess *)sessionSuccessResponseData;
- (void)adjustSessionTrackingFailed:(ADJSessionFailure *)sessionFailureResponseData;
```

I have investigated with Charles proxy, I don't think the events are sent at all. The issue goes away if I:
 - ... move the app into the background by pressing the home button and bring it back
 - ... delete the app and re-run the project on XCode
 - ... enable sending in the background: `[adjustConfig setSendInBackground:YES];`

There are no changes on our integration, only the version has been updated. Is there a known issue/potentially relevant change between the versions?

**Comment by uerceg** [comment]
Hi @ynmehel 

And thanks for detailed report.

Can you maybe send us your SDK initialisation code you have used (while using 4.6.0) and also can you tell us in which place in your application do you run this initialisation code?

**Comment by ynmehel** [comment]
Here's a simplified and modified version. Both methods belong to the same class, which acts as an interface and a convenience layer for the rest of the app providing methods for login state changes, page views and interactions. They all call `trackEventWithToken:dataParamenters:` within their implementations. 

On both versions, I can confirm that `[Adjust appDidLaunch:adjustConfig];`is called on launch and `[self.adjust trackEvent:event];` is called when I want it to track something, but I don't see any packages sent to Adjust server on Charles and do not receive a delegate callback. I have tried modifying `delayStart` and `eventBuffering` with no avail, except for `setSendInBackground:YES`, which seems to fix the problem.

```
- (void)initialize
{
        NSString *environment = ADJEnvironmentProduction;

#if QA_TESTING
        environment = ADJEnvironmentSandbox;
#endif
        ADJConfig *adjustConfig = [ADJConfig configWithAppToken:XYZAdjustUserTrackerAppToken
                                                    environment:environment];
        [adjustConfig setDelegate:self];

#if QA_TESTING
        adjustConfig.logLevel = ADJLogLevelWarn;
#else
        adjustConfig.logLevel = ADJLogLevelAssert;
#endif

        //Debug code thet shows what I have tried
        adjustConfig.logLevel = ADJLogLevelVerbose;
//        adjustConfig.delayStart = 0;
//        adjustConfig.eventBufferingEnabled = !adjustConfig.eventBufferingEnabled;
//        [adjustConfig setSendInBackground:YES];
//        [adjustConfig setSendInBackground:!adjustConfig.sendInBackground];

        [Adjust appDidLaunch:adjustConfig];
}
```

```
- (void)trackEventWithToken:(NSString *)eventToken 
             dataParamenters:(NSDictionary *)eventParameters
{
    ADJEvent *event = [ADJEvent eventWithEventToken:eventToken];
    [event addCallbackParameter:XYZAdjustParameterKey
                          value:self.deviceID];
    [event XYZ_addDataParameters:eventParameters];
    [self.adjust trackEvent:event];
    NSLog(@"Forwarded event '%@' to Adjust sdk", eventToken);
}
```

**Comment by uerceg** [comment]
When you say "is called on launch", does that mean in your `AppDelegate` class inside of `application:didFinishLaunchingWithOptions:` method?

**Comment by ynmehel** [comment]
Not directly, the main project consists of many subfeatures represented by an .xcodeproj. Each project loads its own subprojects and this class belongs to a logging related subfeature.

What I meant was that this happens during launch after a “series of events” but not directly called on `application:didFinishLaunchingWithOptions:`.

**Comment by uerceg** [comment]
Hm. Our SDK is subscribed to iOS system notifications which occur when your application goes out of / back into focus -> `UIApplicationWillResignActiveNotification` and `UIApplicationDidBecomeActiveNotification`. If we assume that you do not have event buffering feature turned ON, or that you maybe enabled offline mode of the SDK, the only thing that can "pause" our SDK from attempting to send packages that have been queued is that for some reason iOS system notification that informs us about your application got out of the focus got fired (this notification also gets fired when you press your home button and application goes to background, for example). If this happened, our SDK will by default just queue things that happen and wait for your app to come back to focus in order to actually make network requests and send those packages.

So maybe question for you -> did you maybe start to show some (login, payment, anything similar to that) screens on your app which you might trigger from some 3rd party sources (like Google, Facebook, etc)? Or in general based on story from above - is there anything that might cause your app to lose focus so that SDK gets paused?

Also what might be helpful maybe is if you maybe could run your app having our SDK set to sandbox mode and log level set to verbose and run your test scenario in which you don't see things getting sent. After that, gather all the `[Adjust]` tagged log lines and send them over so that we can take a better look on what's actually happening SDK wise that causes SDK not to send packages immediately.

**Comment by ynmehel** [comment]
I did this and have a log file ready, is there an email address that I can send this file over?

**Comment by uerceg** [comment]
Sure, feel free to send it over to support@adjust.com and just mention this GitHub issue in the email body so that the mail reaches our SDK team.

Thanks.

**Comment by uerceg** [comment]
@ynmehel 

Did this issue get solved?

**Comment by ynmehel** [comment]
We had dropped the issue temporarily; today a colleague of mine has managed to make it work again using `trackSubsessionStart` on a newer version `.12` instead of `.11`. Closing the issue, thanks for the help.
