### ISSUE TITLE
console warning "Partner parameter value is missing" if I call injectTransactionConfirmedIntoEvent with newCustomer:nil

### ISSUE THREAD

**Issue by sspitzer** [adjust/ios_sdk#311]
Adjust 4.11.0 "Added new partner parameter new_customer to be sent in injectTransactionConfirmedIntoEvent."
I'm not sure what newCustomer is for, so passing in nil

```
[ADJCriteo injectTransactionConfirmedIntoEvent:adjustEvent products:@[productDetails] transactionId:uuid newCustomer:nil];
```
But on my console I see:

```
[Adjust]e: Partner parameter value is missing
```

I can silence this by passing in a string like @"123", but what is newCustomer?  can you silence the warning on nil?

**Comment by uerceg** [comment]
Hi @sspitzer 

Adding partner parameter eventually gets propagated to our SDK which is trying to attach key-value pair specified in the app into event package which is about to be sent to our backend. This warning exists in SDK since long time ago and it's purpose is to inform user that partner parameter key-value pair he specified with `nil` being the value is not going to be added to event package. Sometimes it happens that users simply come to us with complaints that our SDK is not tracking parameters they are attaching and partner callbacks are not getting them. And usually after investigating, it turns out that their logic which determines partner parameter value ends up returning `nil`, thus no parameter attached by our SDK. This log line is actually made so that people get notified if they are doing this unintentionally.

If you are adding `nil` intentionally, I can understand that this warning makes no sense for you, but what is the problem with having this displayed in your logs while testing - the fact itself that message gets displayed (simply annoying) or something else? Our SDK does offer you possibility to set log level above error and skip displaying this and while in production, our SDK will not show logs anyway.

When it comes to `newCustomer` parameter meaning, I will need to follow up on that question, since Criteo code is not part of our official SDK source code, but rather just a plugin which we wrote in cooperation with people from Criteo to support some their specific use cases. Knowledge about semantics of their parameters is something which our client support team is probably aware of so once we get answer from them, will ping you in here.

**Comment by sspitzer** [comment]
Hi @uerceg thanks for the quick reply.  No problem with this, other than I prefer to silence invalid warnings (so I don't ignore new ones.)   Please let me know what you find out from Criteo!

**Comment by uerceg** [comment]
Hey @sspitzer 

It's been quite a while since we last spoke about this one, sorry for that. We never heard back from Criteo on this and in general way how this is implemented in current major version (v4) is probably gonna remain like that. We'll check if we can maybe alter logic regarding this once v5.0.0 is out.

Sorry one more time for not getting back to you on this one.

In case you feel there's need, feel free to comment/reopen.

Cheers
