### ISSUE TITLE
Weak Keychain Protection Class - AccessibleAlways

### ISSUE THREAD

**Issue by kamal-mann** [adjust/ios_sdk#318]
[`AdJKeychain.m` ](https://github.com/adjust/ios_sdk/blob/e1d67b1217207e1438800f0c4427cc1918b1db57/Adjust/ADJKeychain.m#L147) is using  _kSecAttrAccessibleAlways_ which isn't safe.

With `kSecAttrAccessibleAlways` flag the data in the keychain item can always be accessed regardless of whether the device is locked. Recommended way is to use `kSecAttrAccessibleWhenUnlockedThisDeviceOnly` or `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`.

**Comment by uerceg** [comment]
@kamal-mann Thanks for the advice. Information stored in there contains no user/device information, rather just a randomly generated string value. So we went with current approach. 

Is this causing troubles for you having semantic of the stored data in mind or because some of the static code analysis tool reported this to you by running scan on your code base?

**Comment by kamal-mann** [comment]
@uerceg thanks for the prompt reply. It was an error generated from a static analysis tool. Glad to know it's not storing user-specific data. Closing it.
