### ISSUE TITLE
Event failed (Ignoring event subsequent to an event supposed to be unique (first occurred...

### ISSUE THREAD

**Issue by fvonk** [adjust/ios_sdk#326]
Here is my initialization:
```
let adjustConfig = ADJConfig(appToken: <adjustAppToken>, environment: ADJEnvironmentSandbox)
adjustConfig?.logLevel = ADJLogLevelVerbose
Adjust.appDidLaunch(adjustConfig)
```
I don't get any "Install tracked" phrase in log console.

Here is calling event
```
let event = ADJEvent(eventToken: "zxcvzxc")
Adjust.trackEvent(event)
```
Then I get this: 
```
[Adjust]v: Response: {"timestamp":"2018-03-12T09:08:03.069Z+0000","message":"Event failed (Ignoring event subsequent to an event supposed to be unique (first occurred 2018-03-07 08:58:31 +0000 UTC)) (app_token: <adjustAppToken>, adid: <adid>)","error":"Event failed (Ignoring event subsequent to an event supposed to be unique (first occurred 2018-03-07 08:58:31 +0000 UTC)) (app_token: <adjustAppToken>, adid: <adid>)"}
[Adjust]e: Event failed (Ignoring event subsequent to an event supposed to be unique (first occurred 2018-03-07 08:58:31 +0000 UTC)) (app_token: <adjustAppToken>, adid: <adid>)
[Adjust]d: Package handler wrote 0 packages
```

So I don't get any statistics. What can be wrong ?
Thanks

**Comment by uerceg** [comment]
Hi @fvonk 

`Install tracked` message in the log output will be shown to you when you make install of your app with our SDK inside for the first time on your device ever. Every subsequent uninstall/reinstall will be treated as new session (if new session tracking conditions are met, aka more than 30 minutes since last one was tracked). If you want to see `Install tracked` message again upon reinstall, you'd need to forget your test device from our backend and that can be done inside of test console on Adjust dashboard. If you need help with that, feel free to ping your dedicated AM or simply drop us an email on support@adjust.com.

When it comes to event tracking message, that is happening because you have marked your even to be unique on Adjust dashboard, which means that our backend will allow it only to be tracked once on that device. Every subsequent attempt to track that event (after one successful tracking has been done) will result in failure to track it and display that message from above you're seeing. Again, if you wanna see unique event being successfully tracked, you'd need to do the same forget device logic like mentioned above for the `Install tracked` scenario.

If you have any other questions, feel free to ping in here.

Cheers

**Comment by fvonk** [comment]
Great! Thanks for answer @uerceg 

Can you prompt: 
What does this log mean "Skipping duplicate transaction ID <asdfasdf>" ?
Is it okay and event will go to statistics ?
PS. I checked this event is not unique.

**Comment by uerceg** [comment]
@fvonk 

You are probably assigning `transaction ID` to your event that you are attempting to track. Transaction ID is supposed to be unique Apple In-App Purchase identifier. SDK gives you a possibility to assign that value to the event itself. SDK has built in mechanism to remember last 10 transaction IDs assigned to each event and in case we notice that one of them has been repeated for last 10 times, SDK will drop sending of this event completely and won't even send request to our backend. Purpose of this feature is that it serves a small convenient mechanism for deduplication of transaction IDs. When someone's trying to fake In-App Purchase, they often oversee the fact that IDs should be unique and are just trying to reuse same one all the time and our SDK is trying to filter those super dummy fraudulent attempts with this mechanism.

**Comment by fvonk** [comment]
@uerceg 
I see.
Thank you for you help!
