### ISSUE TITLE
Twitter tweets can not open universal link

### ISSUE THREAD

**Issue by z-guohui-qian** [adjust/ios_sdk#337]
We can open universal link in safari from a page we created for example.
But when we tried it in tweeted links, the link would not forward to app and went store page instead.
Please give us some advices.
Thank you.

**Comment by z-guohui-qian** [comment]
And also when we open the the tweeted links in twitter web page in safari, it will jump to application correctly.

**Comment by jonas-adjust** [comment]
Hi @z-guohui-qian unfortunately, the Twitter app does not support Universal Linking. This is because Twitter wraps all links in their own custom subdomain, which results in a redirect from their URL template to the Universal Link. This breaks the logic of the Universal Link so that it can not be resolved properly anymore and leads to the scenario which you are experiencing. 

A redirect from a URL to another Universal Link can only be successful if it is happening either directly in Safari or in Chrome, but not in an in-app environment. This is why the Universal Link is working when you are testing the same scenario from the Twitter webpage in Safari. 

In general, this is a restriction, which is tied to the operating system itself and we are not able to provide any workaround for this. Further restrictions from Universal Links like this one are highlighted in one of our tech blog posts, which you can find [here](http://big-elephants.com/2016-02/dive-into-deep-linking/).

**Comment by z-guohui-qian** [comment]
Thank you for your response!
We found the suggestion for universal link in your document which has old information about universal link in twitter.
This may cause misunderstanding that universal link for twitter is still working.
https://docs.adjust.com/en/universal-links/#building-your-direct-universal-links

**Comment by jonas-adjust** [comment]
@z-guohui-qia Thanks for pointing this out, we are currently in the process of renewing our documentation and I will relay this information to the respective team :).
