### ISSUE TITLE
criteo branch not building with Xcode 10 toolchain

### ISSUE THREAD

**Issue by yhkaplan** [adjust/ios_sdk#347]
Hello, I am unable to build the criteo branch with the Xcode 10 toolchain in Carthage, but the master branch is working. Do you have any update planned or advice to address this? Thanks in advance!

**Comment by uerceg** [comment]
Hi @yhkaplan 

Hm, that is strange. `criteo` branch is completely aligned with `master` branch on our repository, it just contains additionally added `ADJCriteo` h/m files. Is there a way for you to check if version 4.15.0 is the one being used once Carthage pulls from `criteo` branch?

**Comment by uerceg** [comment]
Hi @yhkaplan 

Is it sure that `master` branch is working with Xcode 10 and `criteo` one doesn't? That sounds weird, because IMO either both should or shouldn't work. If Carthage is using some of our post build scripts underneath, then they are not ready for Xcode 10 new build system. We can change them, but then people who are still using Xcode 9 and lower (10 officially came out couple of days ago and lots of our clients aren't really that fast in adopting new versions) there wouldn't be workaround.

Even though on Xcode 10, you can still change Xcode's build system to legacy one and hopefully things should work. You can check instructions from this answer in here: https://stackoverflow.com/a/52386834/1498352

Let us know if it worked for you.

Cheers

**Comment by yhkaplan** [comment]
Thanks for the very quick reply! It appears that I wasn't using the latest version on the criteo branch, which builds fine with Xcode 10/Swift 4.2~ Sorry for the mistake on my part!

**Comment by uerceg** [comment]
🎉 No problemo, glad it worked out. Cheers!
