### ISSUE TITLE
Deeplink don't open directly in the app 

### ISSUE THREAD

**Issue by BrenoVin** [adjust/ios_sdk#351]
I'm implementing Deeplink in my iOS app and I got an issue that the link don't open the app if it was already installed. I already see the issue #268. One behaviour that I noticed was that, in safari the default action is open in AppStore, but if I scroll the page down, I got an banner, with the action to open the app. How can I set this action as a default action? 

![image](https://user-images.githubusercontent.com/7421493/47022547-1d9af800-d134-11e8-99cf-89c037d62636.png)

**Comment by uerceg** [comment]
Hi @BrenoVin 

Troubleshooting deep linking issues usually requires assistance from either our account management or ultimately backend team. In order to reach out to right people as soon as possible, I'd advise you to ask this by sending the question either to your dedicated account manager or to support@adjust.com.

**Comment by ilozano** [comment]
Same problem here. Opening it with Chrome works as expected.

**Comment by humayunharoon** [comment]
^Experiencing the exact same issue.

**Comment by brianendo** [comment]
This issue still exists for me.

**Comment by uerceg** [comment]
Hey guys, closing this one since these kinds of issues are dealt with our support team. Please reach out to your dedicated account manager if you have one or if not, write email to support@adjust.com.

Cheers.
