### ISSUE TITLE
'adjustDeeplinkResponse' not called with deferred deeplink

### ISSUE THREAD

**Issue by Mildwhale** [adjust/ios_sdk#357]
SDK Version: v4.14.3

When I use deferred deeplink 'adjustDeeplinkResponse' is not called.
I have tried to debug your sdk and found that 'ADJAttributionHandler.m: 179' does not generate 'NSURL'.

I can solve the problem by double-encoding 'deeplink', but is there any better way?

There is a example that contain Korean.
**Example**
https://app.adjust.com/myTrackerId?campaign=deferred_deeplink&adgroup=ios&creative=event&deep_link=myapp%3A%2F%2Fmyapp.com%3Fparam1%3Da%26param2%3D%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0%26param3%3Dhttps%3A%2F%2Fwww.google.com

Best Regards,

**Comment by uerceg** [comment]
Hi @Mildwhale 

Is this the link you are using in scenario when deferred deep link callback wasn't called (of course, with proper scheme name instead)?

Did you test deferred deep link with properly uninstalled app and forgotten device from our test console?

**Comment by Mildwhale** [comment]
Hi, @uerceg 

**My test step**
1. Uninstall App
2. Forgotten device from test console
3. Click 'Deferred deep link'
4. Build & Run

When I test deferred deep link without Korean, that works perfectly.

**Comment by uerceg** [comment]
Hi @Mildwhale 

Would it be possible for you to provide me with the link with Korean which causes deferred deep link callback not to get triggered so that I can see it and test it?

Of course, feel free to replace any sensitive info in the link with some dummy values.

**Comment by Mildwhale** [comment]
@uerceg 

There is 2 sample deep link that replaced app scheme.
You need to change 'myTrackerId' and 'myapp'.

**With Korean (not work)**
https://app.adjust.com/myTrackerId?campaign=deferred_deeplink&adgroup=ios&creative=event&deep_link= myapp%3A%2F%2Fmyapp.com%3Fvc%3D12%26v%3Dhed%26t%3D%ED%85%8C%EC%8A%A4%ED%8A%B8%26url%3Dhttps%3A%2F%2Fwww.google.com

**Without Korean (work)**
https://app.adjust.com/myTrackerId?campaign=deferred_deeplink&adgroup=ios&creative=event&deep_link= myapp%3A%2F%2Fmyapp.com%3Fvc%3D12%26v%3Dhed%26t%3Dtest%26url%3Dhttps%3A%2F%2Fwww.google.com

Thanks!

**Comment by uerceg** [comment]
Hi @Mildwhale 

You need to properly encode URL which contains Korean characters, since they need to be double encoded inside of URL.

So your URL from above: https://app.adjust.com/myTrackerId?campaign=deferred_deeplink&adgroup=ios&creative=event&deep_link= myapp%3A%2F%2Fmyapp.com%3Fvc%3D12%26v%3Dhed%26t%3D%ED%85%8C%EC%8A%A4%ED%8A%B8%26url%3Dhttps%3A%2F%2Fwww.google.com

Should look like: https://app.adjust.com/myTrackerId?campaign=deferred_deeplink&adgroup=ios&creative=event&deep_link=adjust-example%3A%2F%2Fmyapp.com%3Fparam1%3Da%26param2%3D%25ED%258C%258C%25EB%259D%25BC%25EB%25AF%25B8%25ED%2584%25B0%26param3%3Dhttps%253A%252F%252Fwww.google.com

**Comment by uerceg** [comment]
In case you still have issues on this topic, feel free to write to your dedicated account manager or at support@adjust.com.

Cheers

**Comment by doolong189** [comment]
To get the referral code value from deeplink from Adjust, do I need to set anything on Adjust and add code command to get that value? Android java/kotlin. Please help me.
