### ISSUE TITLE
Availability of Adjust.attribution()

### ISSUE THREAD

**Issue by christianpbrink** [adjust/ios_sdk#366]
At what point in the app session does `Adjust.attribution()` become non-`nil`? I've been doing a check for it shortly after app launch, and it often isn't available then. Do I need to wait until a specific one of the Adjust SDK callbacks has fired?

To be clear, I'm not talking about the first time the app launches. I'm talking about situations where `adjustAttributionChanged` already fired, many app sessions ago.

Thank you!

**Comment by uerceg** [comment]
Hi @christianpbrink.

That is pretty strange - not to have attribution available with that API on app openings which are not the first one. First question I might have is which SDK version are you using?

Lemme throw some light on how that mechanism in our SDK works. Upon first app opening (and with it first SDK launch ever), SDK is unaware of the attribution of the current user. First thing SDK does is that we send first session package to our backend which is in there treated as install. After that, backend usually replies to SDK to wait a bit (usually couple of seconds) until final attribution for this user is not determined on backend side. After those couple of seconds, SDK asks for final attribution, we get the value from the backend, persist that value in file within app bundle (so that we have it later at any time at our disposal) and we ping attribution callback with that value. With persistence in mind, from this moment on, when ever user invokes public API method for getting attribution value, SDK simply reads the value from the file and provides it as an answer. Until the moment in which we obtain attribution value from the backend, this is the time interval in which invoking attribution getter method would return `nil` as answer. After obtaining it, it should always return non-`nil` value.

With this mechanism in mind, I guess there are theoretical possibilities how can app opening which is not the first one cause `nil` as a return value. Two scenarios come up to my mind right now:

- Lack of internet connectivity during first app opening. For example, either none of the packages got sent because SDK was unable to perform networking requests or maybe install got tracked, but during these couple of seconds internet connectivity became unavailable and SDK wasn't able to perform request to ask backend for attribution. This might result in SDK returning `nil` as a value for longer time than what the normal flow might be.
- Maybe for some reason somehow internal files from bundle got wiped out including file in which we store attribution information and then upon next launch, this info was simply not there.

Reason why I am asking for the SDK version information is that attribution obtaining mechanism was improved some versions in terms of that SDK recognises better these weird scenarios in which we for some reason might end up without attribution information and we added mechanisms for initialising pings to our backend on our own when SDK figures out that it lacks attribution info when it should already have it.

**Comment by christianpbrink** [comment]
Thank you. This is extremely helpful and gave me confidence that you know what you're talking about. I went back to my code and realized that what's happening is in some cases I'm asking for `Adjust.attribution()` before I've called `Adjust.appDidLaunch`. I imagine that could cause this problem — does that sound right?

**Comment by uerceg** [comment]
Unfortunately yes, that is the problem. Invocation of `appDidLaunch` actually initialises our SDK and during that initialisation we read attribution from the storage and load it into memory in case you ask for it. Currently the component which handles all bunch of stuff in our iOS SDK is called attribution handler and if you check in [here](https://github.com/adjust/ios_sdk/blob/master/Adjust/Adjust.m#L390), you'll see that if that component is not initialised (gets initialised as part of `appDidLaunch` flow), you will just get `nil` as an answer.

**Comment by christianpbrink** [comment]
Thank you. I really appreciate the prompt and clear help.

**Comment by uerceg** [comment]
In case you have any further questions in the future on this topic, feel free to reopen the issue. Good luck. Cheers. 🍺
