### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by emrekyv** [adjust/ios_sdk#376]
With iOS support for Swift Package Manager in Xcode 11, is there a way to get that added to the project?

**Comment by florentmorin** [comment]
@emrekyv I think there's a starting point here: https://github.com/adjust/ios_sdk/pull/370

**Comment by gabrielPeart** [comment]
Any progress on this?

**Comment by mayur-ios-dev** [comment]
Any updates here?

**Comment by uerceg** [comment]
👋 Yes, we're currently working on this one, continuing discussion for now on the [PR](https://github.com/adjust/ios_sdk/pull/370). Hopefully should be solved and live soon.

**Comment by ugi** [comment]
Well, turned out that we were working on this one longer than expected, but support for Swift Package Manager should hopefully be there as of just released [v4.23.2](https://github.com/adjust/ios_sdk/releases/tag/v4.23.2). Feel free to give it a shot and comment/reopen in case you encounter any issues.

Thanks for your patience, guys.

Cheers
