### ISSUE TITLE
Call to `UIPasteboard` blocking main thread

### ISSUE THREAD

**Issue by rosecoder** [adjust/ios_sdk#392]
When launching our app with Adjust in the simulator, the app freezes directly. Pausing the debugger points to the Adjust framework and a call to UIPasteboard.

The call is made in UIDevice+ADJAdditions.m, line 101, method adjFbAttributionId:
`result = [UIPasteboard pasteboardWithName:@"fb_app_attribution" create:NO].string;`

This happens randomly. I have not yet seen this on device yet, but when this is blocking our development cycle due to a lot of UI tests fails because of this.

Xcode 11.0 (11A420a)
Simulator is running iOS 13 on iPhone 8.

**Comment by uerceg** [comment]
Hi @rosecoder 

Thanks for reporting. It is pretty hard to chase it on our end as well, since we weren't able to reproduce it. However, from updates we got from our support team, Facebook doesn't depend on this parameter anymore when running campaigns with them since they moved entirely to `idfa` parameter, so we will remove reading of this parameter and these random issues should not appear anymore. Will ping you in here once update is live.

**Comment by uerceg** [comment]
Hey @rosecoder 

We have just released v4.18.3 update (https://github.com/adjust/ios_sdk/releases/tag/v4.18.3) which should hopefully address this issue and solve it for you.

Feel free to give it a try and let us know did it help.

Cheers.

**Comment by rosecoder** [comment]
Hi @uerceg,

Thank you for quick response and quick release.
Looking at the changed code, this would solve the issue. We will open a new issue if a similar issue occurs.

Thanks

**Comment by uerceg** [comment]
Sure thing, fee free to reopen this one in case issue is still there. Cheers!
