### ISSUE TITLE
Cannot trigger deffered deeplink

### ISSUE THREAD

**Issue by mroczkowskij** [adjust/ios_sdk#395]
I'm trying to test deffered deeplink functionality on android. I'm using project on which deffered deeplinks are working correctly on iOS.

My steps:
1) Stop, clean, remove android app
2) Open http://app.adjust.com/forget_device?app_token=(appToken)&adid=(device_adid) -> gives communicate "Forgot device"
3) On android device open link (via email or neocities.org) taken from adjust app center -> project -> tracker -> edit -> CLICK URL
4) Install and open app

At this point I get session and attribution but attribution does not have deeplink. Instead of attribution from 3) I get this:
```
 {
	"app_token": "...",
	"adid": "{correct adid}",
	"timestamp": "...",
	"message": "Attribution found",
	"attribution": {
		"tracker_token": "{tracker token not visible in project}d",
		"tracker_name": "Organic",
		"network": "Organic"
	}
}
```

I tried both ENVIRONMENT_SANDBOX and ENVIRONMENT_PRODUCTION. Also I have 
```
config.setOnDeeplinkResponseListener{
//dummyLog
            true
        } 
```
in my code, although I tried to run it without this part since it's a default value anyway.

Can you spot my error? Do I miss any steps? 

PS. If I run CLICK URL link with installed app then deeplink works correctly

**Comment by uerceg** [comment]
Hi @mroczkowskij 

From this description, can't really spot anything wrong, but need more info.

How does the tracker URL you're clicking onto look like (feel free to omit sensitive parts from it)?

**Comment by mroczkowskij** [comment]
It looks like this
```
https://app.adjust.com/{tracker_id}?label=MariuszTest&deeplink={deeplink}&redirect=http%3A%2F%2Fwww.mtv.co.uk%2F
```
I also tried to add &adid={device_adid} at the end so 
```
https://app.adjust.com/{tracker_id}?label=MariuszTest&deeplink={deeplink}&redirect=http%3A%2F%2Fwww.mtv.co.uk%2F&adid={device_adid}
```

**Comment by uerceg** [comment]
First one won't work unless you have fingerprinting enabled for clicks on your `tracker_id` in dashboard. Second one (this is account management field, so my knowledge might be limited) - I am not sure if `adid` can be used in URL since `adid` is Adjust identifier generated for each device upon receiving install session from it - on click time (prior to install), our backend still doesn't know about this. Maybe you should give it a try with `gps_adid=VALUE` and use `gps_adid` value of your test Android device.

**Comment by mroczkowskij** [comment]
gps_adid instead of adid did the work. Thanks!
