### ISSUE TITLE
Uninstalls not getting tracked

### ISSUE THREAD

**Issue by mkotsiandris** [adjust/ios_sdk#404]
Hello, I am using the latest version of Adjust on iOS and I am having issues with the uninstall events getting tracked. I checked the `README.md` and from what I understand I just need to set properly the push token properly.

```Swift
Adjust.setDeviceToken(deviceToken)
```

I have already done that but it still seems not to work.
Questions:
1. Is that an issue reported by other integrators of the library?
2. Are there any further steps I have to do to resolve that?

Thanks

**Comment by uerceg** [comment]
HI @mkotsiandris 

In order to track uninstalls, you need to have APNs remote notifications setup done properly in your iOS and pass APNs token information to Adjust SDK and in Android FCM push notifications set up properly and FCM token sent to Adjust SDK.

From SDK integration point of view, that's it. If you're sure that you've done that properly, but you are still not getting uninstalls tracked, then I'd advise you to contact either your dedicated account manager or send email with this question to our support team at support@adjust.com and they will be able to better debug the issue and tell you what's up.

In case you have any further SDK related questions, feel free to.

Cheers

**Comment by sagarthecoder** [comment]
Facing the same issue. Uninstall data not being tracked.
Did remote push notification, passed push token to Adjust, and also addedthe  correct p12 file.
Push token is available inside Adjust dashboard, but the uninstall data is not getting tracked.
