### ISSUE TITLE
WIll website know the tracking successed or not when my app both using native tracking and webview bridge?

### ISSUE THREAD

**Issue by Lemonwaterpool** [adjust/ios_sdk#408]
I am now integrating Adjust in my iOS project, with WKWebView page.
I am working on integrate native event tracking(for native button tap etc..),
and AdjustBridge into my website to trigger event tracking(for web button tap etc..).

I am doing well on my app site and web site individually, 
but I find when i mix them together, if I trigger event tracking from my website, my website can't get the log of the event except `adjustConfig` and `adjustEvent`, like the callbackParameters and `Event tracked '{EVENT_TOKEN}` strings, 
But I can see that log on my Xcode's console.

When my app sending  event to Adjust done,  is that any call from my app to my website,
let my website know my app is done with the event tracking, and the detail of that event by default in this SDK?
Or just my integrating problem?

Thanks.

**Comment by uerceg** [comment]
Hi @Lemonwaterpool 

Thanks for detailed explanation. Indeed, when building web bridge extension, we were having mostly use case in mind in which user will use SDK completely from within web view - meaning to initialise it and do all the tracking in there.

However, I think that what you are trying to achieve should still work because at the end of the day, Adjust SDK instance is singleton and it should not really matter where did you initialise it from, native or web view part of your app.

What you can do as a test to see if your events are getting tracked is definitely by checking native SDK logs in Xcode (all your calls to SDK from web view are getting propagated to native SDK instance and if you trigger event and its tracking was submitted to SDK - you should be able to see it in the logs; in case you can generate the logs for your use case and send them over, feel free to and feel free to omit any sensitive information).

**Comment by Lemonwaterpool** [comment]
Thanks for your reply @uerceg 
That helps me a lot.
