### ISSUE TITLE
[Carthage] Invalid tag when running carthage update

### ISSUE THREAD

**Issue by MaximeLM** [adjust/ios_sdk#409]
I have created a Cartfile with the following content:

```
github "adjust/ios_sdk"
```

When I run `carthage update --no-build`, my Cartfile.resolved contains:

```
github "adjust/ios_sdk" "unity4.20.1"
```

I expected Carthage to select the latest stable release, which is v4.20.0.

My guess is that Carthage considers all tags that ends with a version number. Tags that start with a version number but are followed by other characters (e.g. `1.2-alpha-1`) will be ignored (https://github.com/Carthage/Carthage#tag-stable-releases).

**Comment by uerceg** [comment]
Hi @MaximeLM 

And sorry for a bit of delay on this one! Thanks for reporting this, very interesting. I just gave a shot our latest version a shot and got `xamarin4.21.0` checked out by Carthage once cloning latest state of `ios_sdk` repository.

I wanted to ask you if this is actually causing you any issues other than the fact that tag kinda looks weirdly named?

Reason for seeing this tag is that we tend to tag commits on native repos which represent the state of corresponding non native update we did, so that we know what was the state of native SDKs for each of non native updates. This often causes one single commit to be tagged with multiple tags and seems that Carthage "doesn't like it" for some reason and uses one of them when checking out the repository (and obviously not `v4.21.0` which we use as official tag when creating native SDK release).

**Comment by uerceg** [comment]
We'll stop tagging `master` branch with non native SDK tags and I assume that this issue should be resolved. As a matter a fact, you can give our latest SDK update (https://github.com/adjust/ios_sdk/releases/tag/v4.21.1) a shot and hopefully it should check out `v4.21.1` tag.

In case issue is still there, feel free to comment/reopen.

Cheers
