### ISSUE TITLE
Upate Swift Code

### ISSUE THREAD

**Issue by EmreSURK** [adjust/ios_sdk#411]
First, thanks for the awesome product. 
SDK is written in older swift versions' way, better if you update your code.

Here is an example from README;
```
let adjustConfig = ADJConfig.init(
	appToken: yourAppToken,
	environment: ADJEnvironmentSandbox
)
```

We should write the "ADJEnvironmentSandbox" part in that way; "ADJEnvironment.sandbox".
So, we can use in init code like that;

```
let adjustConfig = ADJConfig.init(
	appToken: yourAppToken,
	environment: .sandbox
)
```

It should be converted into an enum from a string, so iOS developers can find the API easily.

**Comment by nonelse** [comment]
Like mentioned in the [other opened issue](https://github.com/adjust/ios_sdk/issues/410#issuecomment-595236749), we are can't really replace our public interface until a new major version update. 
Though, it might be possible to add something, instead of replacing, if they can co-exist at the same time, in a minor update version. Those do happen more or less frequently, so it could be possible to add something like that

**Comment by uerceg** [comment]
Thanks one more time for the advice, we're gonna take this into consideration for next iOS SDK major release (v5.0.0), but we won't do anything about it in v4 to avoid confusion with existing API. Cheers.
