### ISSUE TITLE
Method `adjFbAnonymousId` seems to be not working.

### ISSUE THREAD

**Issue by ren6** [adjust/ios_sdk#415]
Hi! I see in your class `UIDevice+ADJAdditions.m` there is a method `adjFbAnonymousId` which gets fb anonymous id from FB SDK.
I have two concerns:
1) Is it okay to get Facebook's private method from their SDK?
2) This method actually not working when using FBSDK version 6.0 because their method `retrievePersistedAnonymousID` should be called from `FBSDKBasicUtility` class but not from `FBSDKAppEventsUtility`. Are you aware that this is not working anymore?

**Comment by uerceg** [comment]
Hey @ren6 

Thanks for reporting this!

1. It is fine, since this is done in communication with Facebook as part of the MMP program. In case you have further questions, feel free to either reach out to your dedicated account manager or fire an email to support@adjust.com since they will definitely be more suitable to answer questions on this topic.
2. Thanks for pointing this out, we have reached out to FB on this topic and will update SDK accordingly if they inform us that this was intentionally changed with their SDK version 6.0. Will keep you posted.

Cheers

**Comment by uerceg** [comment]
Hi @ren6 

Quick update on this one regarding point 2 from above. FB did some refactoring in their latest major SDK release and our upcoming iOS SDK update will contain fix for that as well. Thank you one more time for pointing this out and will ping you in here once our SDK update is live.

Cheers

**Comment by uerceg** [comment]
Hi @ren6 

And thanks one more time for reporting this. This should now hopefully be fixed in our latest SDK update (https://github.com/adjust/ios_sdk/releases/tag/v4.21.1). In case you notice that issue is still there even with latest SDK version, feel free to comment/reopen.

Cheers
