### ISSUE TITLE
Adjust - Universal Link

### ISSUE THREAD

**Issue by tantran-phdv** [adjust/ios_sdk#430]
i was intergrating universal link to my app. I registered a Associated Domain like this: "applinks:9tze.adj.st" in my xcode. Actually when i open a deeplink, it can open my app but i can not handle the params on that link, the function Adjust.convertUniversalLink(incomingURL, scheme: scheme) return nil also. 
Anybody could give me a reason?

**Comment by uerceg** [comment]
Hi @tantran-phdv 

Can you share in here how does the URL you're clicking onto looks like (the one with universal link and feel free to remove any parameter values which you don't want to share in public) and code of `continueUserActivity` method from your app where you're trying to do this conversion?

Also, which iOS SDK version are you using?

Cheers

**Comment by tantran-phdv** [comment]
`https://app.adjust.com/6d2kayw`. This's my universal link that we generate from Adjust dashboard. And my version sdk is `4.18.3`. Please take a look help me. Thanks for your support!!

**Comment by uerceg** [comment]
Hi @tantran-phdv 

Sorry for a bit delayed response. I am not sure you're testing this properly since tracker URL you're using above won't trigger universal link flow under the hood. Give this tracker URL a shot:

https://app.adjust.com/6d2kayw?deeplink=your-scheme%3A%2F%2F

Let us know if that worked for you.

Cheers

**Comment by tantran-phdv** [comment]
https://app.adjust.com/6d2kayw?deep_link=pizzahutkw://pizza_builder
This is my fully universal link that i using. But itn't working as mention.

**Comment by uerceg** [comment]
Are you using it like this or are you encoding deep link parameter value? Like this, it should not work. Like this (https://app.adjust.com/6d2kayw?deep_link=pizzahutkw%3A%2F%2Fpizza_builder) it should.

**Comment by tantran-phdv** [comment]
Yeb. Actualy i was using the encode parameter value. But it's not working as well

**Comment by uerceg** [comment]
Do you have `pizzahutkw` set as APP SCHEME in Universal Linking setup in dashboard for your app?

**Comment by tantran-phdv** [comment]
Yeb. I did

**Comment by uerceg** [comment]
Yes, but you need to enter just `pizzahutkw` part since `://` is already part of UI. So like this (this is example for one sample app we use):

<img width="246" alt="Screenshot 2020-05-27 at 12 17 59" src="https://user-images.githubusercontent.com/1741635/83007640-41166c00-a014-11ea-9dc0-4427e1e5f4e5.png">

**Comment by tantran-phdv** [comment]
I have check it again and "pizzahutkw" which exactly i set as a APP SCHEME

**Comment by uerceg** [comment]
Hi @tantran-phdv 

If this is still an issue for you, please ping your dedicated account manager or send email to support@adjust.com to continue troubleshooting in there with our support team.

Thanks!

Cheers.
