### ISSUE TITLE
ADJUST_NO_IDFA not working

### ISSUE THREAD

**Issue by sulabh191** [adjust/ios_sdk#444]
with respect to new iOS 14 changes , we want to avoid iOS dialogue ,
so I was trying to add this macro to our Xcode preprocessor Macros in project settings. as :
ADJUST_NO_IDFA=1
but when I run the project  it is always goes to else block .

So how do I correctly configure ADJUST_NO_IDFA macro in Xcode project

**Comment by uerceg** [comment]
Hi @sulabh191 

That's gonna work if you are using our SDK code from source somehow (either adding it manually from the source or maybe using Cocoapods). But if you're using it as a framework, it won't work since frameworks are not compiled with that flag set.

If you want to prevent Adjust SDK from reading IDFA, you can try one of the latest SDK versions and instruct that to the SDK when initialising it:

```objc
[adjustConfig setAllowIdfaReading:NO];
```

If you have any further questions on the topic, feel free to ping.

Cheers

**Comment by uerceg** [comment]
In case you have any further questions, feel free to comment/reopen. Cheers!
