### ISSUE TITLE
i am not getting any LOG in swift

### ISSUE THREAD

**Issue by sahibhussain** [adjust/ios_sdk#449]
i am not getting any log from Adjust. i am using debug mode also

```
let adjustConfig = ADJConfig(appToken: "my_token", environment: ADJEnvironmentSandbox, allowSuppressLogLevel: true)
adjustConfig?.logLevel = ADJLogLevelDebug
Adjust.appDidLaunch(adjustConfig)
```

 Don't know if it is working or not then i try to this

```
let isSDKEnabled = Adjust.isEnabled()

        if isSDKEnabled {
            print("SDK is enabled!")
        } else {
            print("SDK is disabled")
        }
```

i am getting `SDK is enabled` don't know how should i test it

**Comment by ugi** [comment]
Hi @sahibhussain 

You can try setting log level of SDK to verbose instead of debug and simply look at console output of your app when running it. What ever Adjust SDK prints out to the console, it's printed with **[Adjust]** tag in front. If things are getting printed, then it's a solid indicator that SDK is up and running.

Cheers

**Comment by ugi** [comment]
In case you have any further questions, feel free to comment/reopen. Cheers.
