### ISSUE TITLE
SKAdNetwork conversion values handling

### ISSUE THREAD

**Issue by sergiymomot** [adjust/ios_sdk#507]
Hello,

We are preparing for iOS 14.5 release including integration with SKAdNetwork through Adjust SDK, and we have a question regarding how Adjust SDK handles conversion values submission from Adjust servers triggers.

Let's say we set up conversion values to events mapping in Adjust dashboard. To our understanding, once Adjust servers receive an event that is mapped to a conversion value, it will automatically notify Adjust SDK on device about a change, and Adjust SDK will trigger SKAdNetwork's `updateConversionValue` method call.

There is an edge case scenario that we are not clear how Adjust SDK handles:
- **Will conversion value update be triggered if app is in background or is killed?**
So if some event is triggered, but by the time Adjust servers receive that event and notify Adjust SDK about a conversion value update the app is either killed or backgrounded, is there any logic that will attempt to update conversion value after app becomes active/launched again? Or the conversion value update will be lost?

Thanks

**Comment by uerceg** [comment]
HI @sergiymomot 

Use case you are describing is pretty edge casey. Lemme try to explain what will happen in this cases:

- Backgrounded: Adjust SDK is set not to perform any networking logic if the app is in the background. You can change this behavior with [background tracking](https://github.com/adjust/ios_sdk#background-tracking) feature, but default behavior if nothing set is that no network calls will be performed at all. So this is not really a concern for this topic. If app is in background (and let's assume that networking from background is not allowed), SDK simply won't even try to send this event package, but it will wait for app to enter foreground to send it. If SDK sent event package to backend and before it received response from backend, app went to background, that also should not be a concern since SDK will receive response from backend even if app is in background in that moment and call to `updateConversionValue:` will be made.
- Killed: Like said, this is super edge case which I'd honestly expect barely to happen, but nevertheless it is theoretical possibility. If SDK managed to send event package to backend and before receiving response app got killed, that information is not going to be lost. SDK logic works in a way that SDK will dequeue package from our persistent storage only in moment when we received response from backend which indicates that event was tracked successfully. So in this case, upon new initialization, SDK will still have this package queued in storage and try to send it again. Upon successful tracking, backend will send mapped conversion value in response and SDK will dequeue that package + make the call to `updateConversionValue:` method.

Hope I answered your questions. In case you have any other questions, feel free to ask.

Cheers

**Comment by sergiymomot** [comment]
Thanks for a quick reply @uerceg!

You are right that those are very edge case scenarios, for app events.
However, we also send events to Adjust from our backend (through Segment having Adjust as a destination), and we also want those events to be mapped to conversion values. So the chance that our app will be backgrounded or killed during app -> backend -> Segment -> Adjust server -> Adjust SDK sequence of calls is a somewhat higher than for app events.

For example, user creates an account and app makes a request to server. Backend tracks a user created event on success and sends it to Segment which in its turn pipes the event to Adjust.

As you can see, in this case Adjust SDK is not the one who sends an event package.
Is the use case I described even supported by Adjust SDK? And if yes, will Adjust SDK still handle conversion value submission in given scenarios with app being backgrounded or killed?

P.S. It is possible to replace backend event with an app event, however it will lead to duplicate events because we already have everything set up to expect events from backend and having another one coming from apps is suboptimal.

**Comment by uerceg** [comment]
Seems to me that this flow you're describing is some type of `s2s` (server to server) setup. Right now, handling of conversion value updates with s2s approach is being implemented and is not live yet. So this is not supported (yet), but will be soon.

**Comment by sergiymomot** [comment]
Good to hear that it's being worked on
Thanks again!

**Comment by uerceg** [comment]
In case you have any other questions, feel free to comment/reopen. Cheers!
