### ISSUE TITLE
Tracking installs iOS 14.5

### ISSUE THREAD

**Issue by Cr1xus** [adjust/ios_sdk#510]
Hi, we are preparing app to the iOS 14.5 changes and have some questions about Adjust, IDFA and tracking.

1. When application is installed via advertisement, IDFA access is not determined yet. We configure Adjust on app launch, thus IDFA is not determined yet. Then at a later step we ask for a permission (using your wrapper method). In case user allows to use IDFA, will Adjust automatically track install at this step or we need to do something? And what happens if user declined access to the IDFA - does it mean that install will not be tracked by Adjust?

If you have some clear docs that describe this behaviour please give me a link. 

Thanks in advance.

**Comment by uerceg** [comment]
Hi @Cr1xus 

If you initialise Adjust SDK before you show the dialog, it will track install regardless of the fact if your user allows IDFA reading or not. Install will be tracked without IDFA, of course, because at that moment (prior to showing the dialog inside of not determined state) we will not have the IDFA at our disposal. If you decide to start SDK after user allowed IDFA to be collected, then install tracked with SDK in that moment will be tracked with IDFA value attached.

Hope this answers your question. In case you have any further question(s), feel free to ping.

Cheers

**Comment by Cr1xus** [comment]
Hi @uerceg 

Got it, thanks for the prompt response. 

Regards

**Comment by uerceg** [comment]
If needed, feel free to further comment / reopen. Cheers.

**Comment by MarcinWalendowski** [comment]
Hi @uerceg 

From the time of iOS 14.5 public release, we can see some unattributed installs from Adjust in Segment with the below data:

```
@"provider" : @"Adjust",
@"trackerName" : @"No User Consent",
@"trackerToken" : @"unattr"
```

Context: We don't use the ATT framework, but we have SkAdNetwork enabled in Adjust.

Do you maybe know what might be the reason for those unattributed installs?

Thank you!

**Comment by uerceg** [comment]
Hi @MarcinWalendowski 

Sorry for delay in replying in here.

I don't think we're preventing attribution data sending to Segment or anything like that. Values you're seeing are simply values which our backend is setting for users in given situations. Why are those values like that, we who reply in SDK related questions in here are unfortunately not suitable to answer to, so in case you have any further questions on that topic, I'd advise you either ping your dedicated account manager if you have one or if not, send an email to support@adjust.com.

Cheers
