### ISSUE TITLE
Version 4.28.0 /sdk_click 500 error

### ISSUE THREAD

**Issue by dane-thomas-vs** [adjust/ios_sdk#527]
Hello,
I just updated my app to use version 4.28.0 and I noticed that some of the POST requests to /sdk_click are returning a 500 error. This generally happens right after a successful request to the same endpoint. The error in the response is this:
`{
	"timestamp": "2021-04-02T18:51:44.953Z+0000",
	"message": "SDK click failed (failed to handle sdk click) (app_token:{redacted} adid:{redacted})",
	"error": "SDK click failed (failed to handle sdk click) (app_token:{redacted} adid:{redacted})"
}`

I've changed nothing with the implementation and my previous version was 4.22.0 and I did not observe this behavior. Let me know if I can provide more information.

**Comment by dane-thomas-vs** [comment]
Looking further into it there is a difference in the requests. The request for the 200 response has a `details` key in the form. The request for the 500 response does not have `details` but does have `error_code` with a value of `100`.

**Comment by uerceg** [comment]
HI @dane-thomas-vs 

You're seeing that because the jump you made (4.22.0 -> 4.28.0) brought by default enabled feature of handling Apple Search Ads attribution with usage of **AdServices.framework**. Message you're seeing is expected and nothing out of ordinary. It just informs our backend that you don't have **AdServices.framework** integrated inside of your app (useful information on our end in order to help troubleshooting errors when some clients might want to run Apple Search Ads campaign, but failed to integrate **AdServices.framework** for example).

In case you are not interested in this topic, you can disable this logic with Adjust configuration object like this:

```objc
adjustConfig setAllowAdServicesInfoReading:NO];
```

After this, you should stop to see this behaviour.

In case you have any further questions, feel free to ping.

Cheers

**Comment by dane-thomas-vs** [comment]
Wow. Thank you so much for that fast response. I will make that update to the configuration.

**Comment by uerceg** [comment]
👍 Will close this one, but in case there's need, feel free to comment/reopen.

Cheers
