### ISSUE TITLE
[BUG] Native AppTrackingTransparency status change is not recognized

### ISSUE THREAD

**Issue by markusfassbender-parshipgroup** [adjust/ios_sdk#551]
## Context
We use the native `AppTrackingTransparency` framework to ask the user's permissions, because we customized things and also use the results for Firebase and other decisions. 

Unfortunately we see, that Adjust does not automatically detect the result values. From the [documentation](https://github.com/adjust/ios_sdk#att-framework) I understood, that this should work:
> The SDK has a built-in mechanism to receive an updated status after a user responds to the pop-up dialog

After another app start, the value is set correctly. But we don't track the first app start / registration anymore, which is very important for us.

## Solution Idea
Beside the getter `appTrackingAuthorizationStatus()` I would suggest to implement a method to manually update the value like `setAppTrackingAuthorizationStatus(_ status: ATTrackingManager.AuthorizationStatus)`.

Maybe other ideas come up?

**Comment by uerceg** [comment]
Hi @markusfassbender-parshipgroup 

Thanks for the detailed explanation. And yes, in theory if you would be using our SDK's wrapper method to show ATT dialog, upon answering we would be able to detect the change in authorization status immediately (obviously). But if you're using native ATT dialog, then we will pick up this information, but at most probably a bit delayed time. 

Your suggestion sounds interesting, we'll forward it to the product team, but actually I'm curious to understand how exactly your setup in app looks like and where the issue is? When are you showing the dialog? When are you initializing SDK relative to ATT dialog? Which moment is the one where data which our SDK sends is being used by you for Firebase and these other things?

**Comment by markusfassbender-parshipgroup** [comment]
Sorry for my late reply. It seemed that a implementation specific timing in our code base caused the bug. Thank you

**Comment by sohail-dragon** [comment]
Hey @markusfassbender-parshipgroup would love if you could mention in brief what caused the issue on your end. We're facing the same problem that the ATT status isn't getting picked up by the Adjust SDK.

**Comment by uerceg** [comment]
👋 @sohail-dragon 

Can you maybe in the meantime while waiting for Markus' response explain how does your test look like in which you're noticing that Adjust SDK is not picking up the ATT status? Like what steps are you performing and what do you see that it's happening vs. what you expected to see?

**Comment by sohail-dragon** [comment]
> 👋 @sohail-dragon
> 
> Can you maybe in the meantime while waiting for Markus' response explain how does your test look like in which you're noticing that Adjust SDK is not picking up the ATT status? Like what steps are you performing and what do you see that it's happening vs. what you expected to see?

Sorry @uerceg, missed your reply. You can have a look at this comment https://github.com/adjust/ios_sdk/issues/564#issuecomment-926423876. Like I mentioned in the comment, I have sent over a detailed repro to adjust support. Will it be possible to get it from there?
