### ISSUE TITLE
trackerToken is "unattr" in adjustAttributionChanged(_:)

### ISSUE THREAD

**Issue by yukimatsus** [adjust/ios_sdk#580]
After click tracker url, I expect to receive tracker token in `adjustAttributionChanged(_:)` but receive "unattr".
Are there any missing steps?

I have tried as following.

　Forget device in dashboard and uninstall my app.
　↓
　Click tracker URL `https://app.adjust.com/xxxxxx/?campaign=test_campaign`. And app store opens.
　↓
　Install my app to iOS Device by Xcode Run.
　↓
　Tracker token is `xxxxxx` in [dashboard > Test Console > View Device Data], **but** is "unattr" in `adjustAttributionChanged(_:)`.

```
extension AppDelegate: AdjustDelegate {
    func adjustAttributionChanged(_ attribution: ADJAttribution?) {
        print("***** trackerToken: \(attribution?.trackerToken)")
        print("***** campaign: \(attribution?.campaign)")
        print("***** attribution: \(attribution)")
    }
}
```

```
***** trackerToken: Optional("unattr")
***** campaign: nil
***** attribution: Optional(tt:unattr tn:No User Consent net:No User Consent cam:(null) adg:(null) cre:(null) cl:(null) adid:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ct:(null) ca:(null) cc:(null))
```

- Adjust SDK Version: 4.29.6
- StoreKit.framework is included.(for SKAdNetwork)
- This occurs when both sandbox mode and production mode.
- iOS 15.0 (device)
- ATT is opted in.

Thanks.

**Comment by uerceg** [comment]
Hey @yukimatsus 

Thank you for detailed explanation. Unfortunately we (devs) can't help you much with this topic in here, especially since it would require to provide us with some details about your app which might not be something you would like to share in public repo. I'd suggest to write to your dedicated account manager if you have one or if not, to support@adjust.com and reference this GitHub issue with details in there and someone from our support team will inspect logs for your device and let you know what's up.

Cheers!

**Comment by ykkd** [comment]
@uerceg 
Hi, I am facing same issue.
If it's possible, could you tell me how you've solved this?
