### ISSUE TITLE
[Crash] Crash at `[ADJUtil writeObject:fileName:objectName:syncObject:]`

### ISSUE THREAD

**Issue by dongshuju** [adjust/ios_sdk#608]
SDK Version: v4.29.7

Crash info:
```
Crashed：io.adjust.PackageQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x2ee80 _CFArrayReplaceValues + 976
1  CoreFoundation                 0x52cbc CFArrayAppendValue + 156
2  CoreFoundation                 0x2da24 _flattenPlist + 272
3  CoreFoundation                 0x2dbfc _flattenPlist + 744
4  CoreFoundation                 0x2db98 _flattenPlist + 644
5  CoreFoundation                 0x2dbfc _flattenPlist + 744
6  CoreFoundation                 0x2db98 _flattenPlist + 644
7  CoreFoundation                 0x11b04 __CFBinaryPlistWriteOrPresize + 236
8  Foundation                     0x55888 -[NSKeyedArchiver finishEncoding] + 544
9  Foundation                     0x95b6c -[NSKeyedArchiver encodedData] + 72
10 Foundation                     0x308d0 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 120
11 Adjust                         0x3ac9c +[ADJUtil writeObject:fileName:objectName:syncObject:] + 337 (ADJUtil.m:337)
12 Adjust                         0x2c380 -[ADJPackageHandler writePackageQueueS:] + 324 (ADJPackageHandler.m:324)
13 Adjust                         0x2b928 -[ADJPackageHandler addI:package:] + 218 (ADJPackageHandler.m:218)
14 Adjust                         0x3d570 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 813 (ADJUtil.m:813)
15 libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
17 libdispatch.dylib              0xa738 _dispatch_lane_serial_drain$VARIANT$mp + 644
18 libdispatch.dylib              0xb1f0 _dispatch_lane_invoke$VARIANT$mp + 408
19 libdispatch.dylib              0x14ec4 _dispatch_workloop_worker_thread + 632
20 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
21 libsystem_pthread.dylib        0x193c start_wqthread + 8
```

**Comment by dongshuju** [comment]
Update to latest SDK Version 4.30.0 still crash

**Comment by 405092901** [comment]
So do i，fix this bug as soon as possible please

**Comment by ParveenTyagi2389** [comment]
we are also getting crash due to same issue.

SDK version : 4.30.0

Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x36550 _CFArrayReplaceValues + 840
1  CoreFoundation                 0x3594c CFArrayAppendValue + 232
2  CoreFoundation                 0x433c4 _flattenPlist + 292
3  CoreFoundation                 0x43568 _flattenPlist + 712
4  CoreFoundation                 0x43500 _flattenPlist + 608
5  CoreFoundation                 0x43568 _flattenPlist + 712
6  CoreFoundation                 0x43500 _flattenPlist + 608
7  CoreFoundation                 0x42f44 __CFBinaryPlistWriteOrPresize + 236
8  Foundation                     0x1b930 -[NSKeyedArchiver finishEncoding] + 548
9  Foundation                     0x1cba4 -[NSKeyedArchiver encodedData] + 76
10 Foundation                     0x1bfdc +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 124
11 Adjust                         0x3e8e4 +[ADJUtil writeObject:fileName:objectName:syncObject:] + 337 (ADJUtil.m:337)
12 Adjust                         0x2fd78 -[ADJPackageHandler writePackageQueueS:] + 324 (ADJPackageHandler.m:324)
13 Adjust                         0x2f320 -[ADJPackageHandler addI:package:] + 218 (ADJPackageHandler.m:218)
14 Adjust                         0x411d4 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 813 (ADJUtil.m:813)
15 libdispatch.dylib              0x2a84 _dispatch_call_block_and_release + 32
16 libdispatch.dylib              0x481c _dispatch_client_callout + 20
17 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
18 libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
19 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
20 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
21 libsystem_pthread.dylib        0xa74c start_wqthread + 8

**Comment by dongshuju** [comment]
We have removed the AdjustSDK to resolve this problem

**Comment by ParveenTyagi2389** [comment]
We are still getting that crash reported in firebase crashlytics. 
When it will be fixed.

**Comment by ab-rdarts** [comment]
Adjust cannot fix this problem for years though it's not so frequent

**Comment by uerceg** [comment]
Hi guys,

Can you please give [latest iOS SDK v4.33.4 update](https://github.com/adjust/ios_sdk/releases/tag/v4.33.4) a shot and let us know if this issue still appears with that version? We have gotten confirmation from one client that changes we introduced in this SDK update (and which client tried prior to this release) caused their app not to see crashes with this same stack trace anymore. Looking forward to hear back from you on this one.
