### ISSUE TITLE
Updated attribution didn't work

### ISSUE THREAD

**Issue by ZyaireShu** [adjust/ios_sdk#656]
Hey Guys.I got a problem while using Adjust.

  I am working on my app which needs to get TrackerName from attribution.But I keep getting "**No User Consent**" from _Adjust.attribution()_  unless I remove the app and reinstall it.

I have registed a delegate callback properly. According to the document 

> We also send updated attribution information after an iOS 14.5+ device's ATT status changes to Authorized.

I thought when att status changed the adjustAttributionChanged method will be called so that i can get the correct TrakerName .
But now after the att status changed to Authorized. I have to uninstall and install the app , adjustAttributionChanged can be called.

By the way Iam using the [App-tracking authorization wrapper] to request authorization.
Is anybody able to help me?

**Comment by uerceg** [comment]
Hi @ZyaireShu,

Thank you for detailed description. Even though I am not 100% sure, what seems to me that it might be happening is this:

1. You might be initializing Adjust SDK first (making a call to `appDidLaunch` method).
2. After you made an initialization call, you are showing ATT dialog.
3. Under the hood (since the initialization flow has already started), SDK is managing to track an install session + ask backend about final attribution for the device prior to ATT dialog being answered to and communicating information about the answer to our backend to take that new ATT status into consideration for the initial attribution which SDK will get as a response from backend.
4. In this state of the things, attribution callback you mentioned will be pinged with the attribution value which states that no consent was obtained from this device (call to `Adjust.attribution()` is just a getter which will return locally stored value which SDK got once it pinged the attribution callback, so that won't cause any kind of a "refresh" call to our backend to check whether attribution might have changed in the meantime.

Like said, it's just an assumption, not sure if that's happening exactly in your app. But what might be a good test to make sure that timing wise everything works as it should and double check if you'd be getting proper attribution is following:

1. Uninstall the app from your test device.
2. Forget your test device from Adjust testing console.
3. Move SDK initialization into the callback method of the Adjust ATT wrapper method (which you mentioned that you're using). So pretty much make sure that ATT dialog is answered before SDK is initialized.
4. Initialize SDK from there and double-check whether attribution value is what you expect it to be.

In case you have any further questions or doubts on this topic, feel free to ping.

Cheers

**Comment by ZyaireShu** [comment]
Problem solved thank you!!

**Comment by graboosky** [comment]
@ZyaireXv  How did you solved that? Seems I have exact same issue.
