### ISSUE TITLE
The app references non-public selectors in Payload/XXX.app/XXX: getVersion

### ISSUE THREAD

**Issue by kr1s0404** [adjust/ios_sdk#658]
When I upload my App to the AppStore, it shows the error.

![截圖 2023-03-16 下午6 37 25](https://user-images.githubusercontent.com/83443996/225592072-6aa1e01b-b5a5-4b05-b1be-c40997ce09a9.png)

I search "Payload" and "getVersion" in my Xcode project, I found this issuse might be caused by Adjust SDK, but I am not sure.
The error was shown when I submit my app to AppStore, it won't come up when compile or build.
![截圖 2023-03-16 下午6 34 38](https://user-images.githubusercontent.com/83443996/225592626-aeb86d9c-8c11-4608-994f-952bc3cf42b1.png)
![截圖 2023-03-16 下午6 35 26](https://user-images.githubusercontent.com/83443996/225592643-df9fb458-0263-4b54-9e2c-bc6186434139.png)

**Comment by uerceg** [comment]
Hi @kr1s0404,

Thank you for your report. Hm, interesting. I would assume that `Payload` in this case simply refers to a bundle which you are trying to upload to App Store Connect. `getVersion` indeed sounds like a name of the method which we are trying to access via reflection (because that API might not be present for each app, depending on integration), but it's actually our (Adjust) API which is also publicly defined in a header file. It's by no means private in our implementation nor some kind of a private iOS API which we are accessing in here.

Quick search points initially to the [ticket](https://developer.apple.com/forums/thread/714736) opened in Apple developer forums where it seems like with update to Xcode 14, issues of this kind have started to pop up more and more. Just out of curiosity, are you using Xcode 14 as well in this case? I am not sure at this moment what is the way to make this error go away, but we'll try to see if we can reproduce this internally on our end.

**Comment by kr1s0404** [comment]
Yes, I'm using Xcode 14. This error doesn't effect my app or cause any issues, my app works fine. Thank you for the feedback!

**Comment by kr1s0404** [comment]
Quick Update: This issue was resolve after I update my Xcode to 14.3

**Comment by uerceg** [comment]
Amazing, glad to hear this. Thank you very much for the update on this one. Cheers!
