### ISSUE TITLE
Apple Privacy Manifest File

### ISSUE THREAD

**Issue by mattiacantalu** [adjust/ios_sdk#693]
Any update about the [privacy manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)?

**Comment by Aditi3** [comment]
Hi @mattiacantalu 

We're currently testing out the beta version of our SDK with the new iOS 17 & privacy manifest changes. 

If you're interested in being part of our beta SDK testing, you can contact your respective Customer Support person from our team, and they'll be happy to give you all the details.

**Comment by ThomWee** [comment]
How is the test going? I'm looking forward for the next official release including the Privacy Manifest file.

**Comment by Aditi3** [comment]
Hi @ThomWee, 

We are still in the process of verifying the beta version of our SDK. Nonetheless, next up in our iOS releases is the Privacy Manifest changes. I will let you know the timeline as soon as we finalize it internally.

**Comment by noangel** [comment]
Sorry, but I don't know where to ask. I'm trying to use older Adjust SDK and going to add privacy manifest and merge SDK items to my app. I found that my app trying to connect app.adjust.com/<...> and URL looks like there is some tracking. I found it using Xcode network profiler( https://developer.apple.com/documentation/xcode/detecting-when-your-app-contacts-domains-that-may-be-profiling-users ), but it doesn't display in "Points of Interest" view.
What do You think should I add "app.adjust.com" to privacy manifest NSPrivacyTrackingDomains or it should be fine as is? And if I should to add it, is it the only tracking domain or there are more in Adjust SDK?
I also use Firebase and its "app-measurement.com" is detected, so added it to tracking domains.

**Comment by Aditi3** [comment]
Hi @noangel 

Thank you for reaching out. I suggest not adding our URL "[app.adjust.com](http://app.adjust.com/)" to the privacy manifest under NSPrivacyTrackingDomains. It should be all right not to have it configured because our URL isn't marked under the **Points of Interest** track. Additionally, Apple has not included our iOS SDK in the [list of third-party SDKs](https://developer.apple.com/support/third-party-SDK-requirements/) that require a privacy manifest. That means our clients can publish or update new apps with our iOS SDK without including a privacy manifest.

Nonetheless, we will include our own privacy manifest in the upcoming version of SDK releases to provide better clarity to users, but as of now, it is not necessary to include any configuration related to the Adjust SDK in your application's privacy manifest file.

I hope this is helpful!

**Comment by noangel** [comment]
@Aditi3 Thank You very much for clear answer!

**Comment by pavm035** [comment]
@Aditi3 Any idea when new SDK with privacy manifest will be included?

**Comment by Aditi3** [comment]
We plan to release the SDK with iOS 17 and Privacy Manifest either this week or early next week. Thank you everyone for your patience.

**Comment by pavm035** [comment]
@Aditi3  any updates on relase?

**Comment by Aditi3** [comment]
Hi Everyone,

Apologies for the delay in releasing our iOS 17 changes. Unfortunately, our solution faced some setbacks during testing, causing a week's delay in release. We are doing everything possible to resolve these issues and release the update as soon as possible. 

Thank you again for your patience, and will keep you updated on our progress and release.

**Comment by Aditi3** [comment]
Hi Everyone,

We've released the SDK with iOS 17 and Privacy Manifest support. 

Here's the link - https://github.com/adjust/ios_sdk/releases/tag/v4.38.0

Thanks again for your patience.

**Comment by zhangqiankun6** [comment]
Where can I download AdjustSdk-iOS-Static.framework.zip

**Comment by sylvia-tencent-wmt** [comment]
What about the AdjustSigSdk? Is there any updates regarding the Privacy Manifest support?
Url: https://github.com/adjust/adjust_signature_sdk

**Comment by Aditi3** [comment]
Hi @zhangqiankun6,

The Privacy Manifest file is a resource bundle that cannot be added to static frameworks. Hence, the distribution of static frameworks has been deprecated since version 4.38.0.

I hope this helps.

**Comment by tani-shi** [comment]
Adjust's official document says that no need to include privacy manifest if our app contains only adjust sdk.
https://help.adjust.com/en/article/submit-privacy-details-to-apple

However, the latest version contains the privacy manifest with some of tracking domains and reasons.
https://github.com/adjust/ios_sdk/commits/c25fd630810b3f91f8c95f55006058320adfa950/Adjust/PrivacyInfo.xcprivacy

I don't think it's correct a reason why not to need include privacy manifest by adjust-sdk is not contained in the listed sdks.
https://developer.apple.com/support/third-party-SDK-requirements/

Considering above, I suspect there might be a discrepancy due to the adjustments made to the PrivacyManifest within the last week. Would that be a correct assumption?

![Screenshot 2024-03-28 at 17 03 51](https://github.com/adjust/ios_sdk/assets/18569920/f5a81fb8-c8af-4afe-a9e7-6bdcb06481b5)

**Comment by Aditi3** [comment]
Hi @tani-shi 

Thank you for reaching out. That's right, our SDK version 4.38.0 now supports the Privacy Manifest to provide better clarity to users. 

Thank you for bringing this to our attention. We will update our help center guide accordingly.

**Comment by Aditi3** [comment]
We've updated our Help Center guide to reflect the changes. Thanks again @tani-shi, for pointing this out.

**Comment by tani-shi** [comment]
@Aditi3 
Thanks for your quick respond and updates.
Gonna notice our team.

**Comment by pavm035** [comment]
Hi @Aditi3  
We updated adjust SDK to v4.38.0 and we found that some tracking domains changed for example previous version we were checking `app.adjust.com` but in new version it's `consent.adjust.com` looks like this change might impact our users since we are doing some deeplink procssing from adjust based on the former domain, any soltuion to this?

**Comment by Aditi3** [comment]
Hi @pavm035, Could you please provide us with an example or code snippet showing how this affects deep link functionality on your side to help you better here?

As we understand, this domain change shouldn't affect deep link handling or any related functionality.
