### ISSUE TITLE
Umbrella header cannot be found using cocoa pods

### ISSUE THREAD

**Issue by egarni** [adjust/ios_sdk#728]
Hello, I'm trying to update to version 5 using CocoaPods, and I'm getting this error:
```
Pods/Adjust/ModuleMap/module.modulemap:2:19: error: umbrella header 'AdjustSdk.h' not found
  umbrella header "AdjustSdk.h"
                  ^
<unknown>:0: error: could not build Objective-C module 'AdjustSdk'
```

Anything you are aware of?

**Comment by Aditi3** [comment]
Hi @egarni ,

Could you try running `pod update` command for your application and let us know if that helps?

**Comment by egarni** [comment]
Still the same
![Screenshot 2024-09-04 at 08 32 58](https://github.com/user-attachments/assets/20d478d6-5537-4084-bbab-e14d358c5943)

**Comment by genadyb** [comment]
Hello, @egarni.
In order to fully understand the issue, we would like to ask you to provide us with more details about your integration.
- Where are you integrating Adjust SDK, application / other SDK / etc.?
- What platform are you targeting?
- What is the language of your consumer App / SDK / etc.?
- What version of Adjust SDK had you used before you tried to update to a V5?
- Please share here the Podfile you are using to integrate Adjust SDK.
- How did you perform the update process? What steps have gone through?

We will try to understand the issue and help you as fast as possible.
Thank you.

**Comment by genadyb** [comment]
@egarni 
Thank you for the information.
We will re-check it shortly and let you know.

**Comment by egarni** [comment]
I can see that a fix has been made [here](https://github.com/adjust/ios_sdk/pull/734)
I updated to version 5.0.1, and it now I can compile. So everything is good now, thank for looking into the issue 👍

**Comment by uerceg** [comment]
Hey @egarni,

Thank you very much for the feedback. We did encounter similar (but it seems related to yours) issue, but we were unsure if yours is also affected by that or not. Good to know that 5.0.1 solves your problem as well.

Thank you one more time for reporting and for all the feedback in here.

Cheers.
