### ISSUE TITLE
Consultation on the usage issues of the Adjust.adid {} method.

### ISSUE THREAD

**Issue by zhangfurun** [adjust/ios_sdk#743]
In version 4.x, adid could be retrieved synchronously. After upgrading to version 5.x, it has become asynchronous.

So there are three points of concern:
	1.	Is the retrieval of the adid a one-time asynchronous callback, or does it work as a continuous asynchronous callback (similar to being in a listening state after setting the method)?
	2.	Does this method retrieve the adid before or after Adjust.initSdk(config) is initialized?
	3.	Is it possible for the retrieved value to be null?

**Comment by uerceg** [comment]
Hey @zhangfurun,

Thank you for reaching out.

1. Getter for `adid` is a one time callback, not a subscription type (like attribution callback is, for example). In [this issue](https://github.com/adjust/ios_sdk/issues/740) it was discussed a bit more in detail around this topic, so you might find some interesting things to read about behavior and reasoning for the change.
2. In the current implementation, `adid` getter always expects SDK to be initialized in order to return the value. If invoked before the initialization, your callback will be cached and pinged with the value after the SDK gets initialized.
3. Good question, this is what the discussions around v5 implementation were mostly about, but that aside - it is not possible to get this callback triggered with `null` value (this was the biggest v4 complaint for many which we were trying to solve with v5 approach).

In case you have any other questions or doubts, feel free to ping.

Cheers

**Comment by zhangfurun** [comment]
@uerceg Thank you for your reply. I understand.
